package com.example.muslim;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;

public class QuranExplanation_56Activity extends AppCompatActivity {

    ArrayList<AlwakeaEx> alwakeaExes = new ArrayList<>();
    RecyclerView recyclerView;
    quran_explanation_56_adapter quran_explanation_56_adapter;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_quran_explanation_56);

        alwakeaExes.add(new AlwakeaEx("بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ"));
        alwakeaExes.add(new AlwakeaEx("إِذَا وَقَعَتِ الْوَاقِعَةُ (1)"));
        alwakeaExes.add(new AlwakeaEx("إذا قامت القيامة."));
        alwakeaExes.add(new AlwakeaEx("لَيْسَ لِوَقْعَتِهَا كَاذِبَةٌ (2)"));
        alwakeaExes.add(new AlwakeaEx("ليس لقيامها أحد يكذِّب به"));
        alwakeaExes.add(new AlwakeaEx("خَافِضَةٌ رَافِعَةٌ (3)"));
        alwakeaExes.add(new AlwakeaEx("هي خافضة لأعداء الله في النار، رافعة لأوليائه في الجنة."));
        alwakeaExes.add(new AlwakeaEx("إِذَا رُجَّتِ الْأَرْضُ رَجًّا (4)"));
        alwakeaExes.add(new AlwakeaEx("إذا حُرِّكت الأرض تحريكًا شديدًا."));
        alwakeaExes.add(new AlwakeaEx("وَبُسَّتِ الْجِبَالُ بَسًّا (5)"));
        alwakeaExes.add(new AlwakeaEx("وفُتِّتت الجبال تفتيتًا دقيقًا."));
        alwakeaExes.add(new AlwakeaEx("فَكَانَتْ هَبَاءً مُنْبَثًّا (6)"));
        alwakeaExes.add(new AlwakeaEx("فصارت غبارًا متطايرًا في الجو قد ذَرَتْه الريح."));
        alwakeaExes.add(new AlwakeaEx("وَكُنْتُمْ أَزْوَاجًا ثَلَاثَةً (7)"));
        alwakeaExes.add(new AlwakeaEx("وكنتم -أيها الخلق- أصنافًا ثلاثة:"));
        alwakeaExes.add(new AlwakeaEx("فَأَصْحَابُ الْمَيْمَنَةِ مَا أَصْحَابُ الْمَيْمَنَةِ (8)"));
        alwakeaExes.add(new AlwakeaEx("فأصحاب اليمين، أهل المنزلة العالية، ما أعظم مكانتهم!!"));
        alwakeaExes.add(new AlwakeaEx("وَأَصْحَابُ الْمَشْأَمَةِ مَا أَصْحَابُ الْمَشْأَمَةِ (9)"));
        alwakeaExes.add(new AlwakeaEx("وأصحاب الشمال، أهل المنزلة الدنيئة، ما أسوأ حالهم!!"));
        alwakeaExes.add(new AlwakeaEx("وَالسَّابِقُونَ السَّابِقُونَ (10)"));
        alwakeaExes.add(new AlwakeaEx("والسابقون إلى الخيرات في الدنيا هم السابقون إلى الدرجات في الآخرة."));
        alwakeaExes.add(new AlwakeaEx("أُولَئِكَ الْمُقَرَّبُونَ (11)"));
        alwakeaExes.add(new AlwakeaEx("أولئك هم المقربون عند الله."));
        alwakeaExes.add(new AlwakeaEx("فِي جَنَّاتِ النَّعِيمِ (12)"));
        alwakeaExes.add(new AlwakeaEx("يُدْخلهم ربهم في جنات النعيم."));
        alwakeaExes.add(new AlwakeaEx("ثُلَّةٌ مِنَ الْأَوَّلِينَ (13)"));
        alwakeaExes.add(new AlwakeaEx("يدخلها جماعة كثيرة من صدر هذه الأمة، وغيرهم من الأمم الأخرى."));
        alwakeaExes.add(new AlwakeaEx("وَقَلِيلٌ مِنَ الْآخِرِينَ (14)"));
        alwakeaExes.add(new AlwakeaEx("وقليل من آخر هذه الأمة."));
        alwakeaExes.add(new AlwakeaEx("عَلَى سُرُرٍ مَوْضُونَةٍ (15)."));
        alwakeaExes.add(new AlwakeaEx("على سرر منسوجة بالذهب."));
        alwakeaExes.add(new AlwakeaEx("مُتَّكِئِينَ عَلَيْهَا مُتَقَابِلِينَ (16)"));
        alwakeaExes.add(new AlwakeaEx("متكئين عليها يقابل بعضهم بعضًا."));
        alwakeaExes.add(new AlwakeaEx("يَطُوفُ عَلَيْهِمْ وِلْدَانٌ مُخَلَّدُونَ (17)"));
        alwakeaExes.add(new AlwakeaEx("يطوف عليهم لخدمتهم غلمان لا يهرمون ولا يموتون."));
        alwakeaExes.add(new AlwakeaEx("بِأَكْوَابٍ وَأَبَارِيقَ وَكَأْسٍ مِنْ مَعِينٍ (18)"));
        alwakeaExes.add(new AlwakeaEx("بأقداح وأباريق وكأس من عين خمر جارية في الجنة."));
        alwakeaExes.add(new AlwakeaEx("لَا يُصَدَّعُونَ عَنْهَا وَلَا يُنْزِفُونَ (19)"));
        alwakeaExes.add(new AlwakeaEx("لا تُصَدَّعُ منها رؤوسهم، ولا تذهب بعقولهم."));
        alwakeaExes.add(new AlwakeaEx("وَفَاكِهَةٍ مِمَّا يَتَخَيَّرُونَ (20)"));
        alwakeaExes.add(new AlwakeaEx("ويطوف عليهم الغلمان بما يتخيرون من الفواكه."));
        alwakeaExes.add(new AlwakeaEx("وَلَحْمِ طَيْرٍ مِمَّا يَشْتَهُونَ (21)"));
        alwakeaExes.add(new AlwakeaEx("وبلحم طير ممَّا ترغب فيه نفوسهم."));
        alwakeaExes.add(new AlwakeaEx("وَحُورٌ عِينٌ (22)"));
        alwakeaExes.add(new AlwakeaEx("ولهم نساء ذوات عيون واسعة."));
        alwakeaExes.add(new AlwakeaEx("كَأَمْثَالِ اللُّؤْلُؤِ الْمَكْنُونِ (23)"));
        alwakeaExes.add(new AlwakeaEx("كأمثال اللؤلؤ المصون في أصدافه صفاءً وجمالا."));
        alwakeaExes.add(new AlwakeaEx("جَزَاءً بِمَا كَانُوا يَعْمَلُونَ (24)"));
        alwakeaExes.add(new AlwakeaEx("جزاء لهم بما كانوا يعملون من الصالحات في الدنيا."));
        alwakeaExes.add(new AlwakeaEx("لَا يَسْمَعُونَ فِيهَا لَغْوًا وَلَا تَأْثِيمًا (25)"));
        alwakeaExes.add(new AlwakeaEx("لا يسمعون في الجنة باطلا ولا ما يتأثمون بسماعه."));
        alwakeaExes.add(new AlwakeaEx("إِلَّا قِيلًا سَلَامًا سَلَامًا (26)"));
        alwakeaExes.add(new AlwakeaEx("إلا قولا سالمًا من هذه العيوب، وتسليم بعضهم على بعض."));
        alwakeaExes.add(new AlwakeaEx("وَأَصْحَابُ الْيَمِينِ مَا أَصْحَابُ الْيَمِينِ (27)"));
        alwakeaExes.add(new AlwakeaEx("وأصحاب اليمين، ما أعظم مكانتهم وجزاءهم!!"));
        alwakeaExes.add(new AlwakeaEx("فِي سِدْرٍ مَخْضُودٍ (28)"));
        alwakeaExes.add(new AlwakeaEx("هم في سِدْر لا شوك فيه."));
        alwakeaExes.add(new AlwakeaEx("وَطَلْحٍ مَنْضُودٍ (29)"));
        alwakeaExes.add(new AlwakeaEx("وموز متراكب بعضه على بعض."));
        alwakeaExes.add(new AlwakeaEx("وَظِلٍّ مَمْدُودٍ (30)"));
        alwakeaExes.add(new AlwakeaEx("وظلٍّ دائم لا يزول."));
        alwakeaExes.add(new AlwakeaEx("وَمَاءٍ مَسْكُوبٍ (31)"));
        alwakeaExes.add(new AlwakeaEx("وماء جار لا ينقطع."));
        alwakeaExes.add(new AlwakeaEx("وَفَاكِهَةٍ كَثِيرَةٍ (32)"));
        alwakeaExes.add(new AlwakeaEx("وفاكهة كثيرة."));
        alwakeaExes.add(new AlwakeaEx("لَا مَقْطُوعَةٍ وَلَا مَمْنُوعَةٍ (33)"));
        alwakeaExes.add(new AlwakeaEx("وفاكهة كثيرة لا تنفَد ولا تنقطع عنهم، ولا يمنعهم منها مانع."));
        alwakeaExes.add(new AlwakeaEx("وَفُرُشٍ مَرْفُوعَةٍ (34)"));
        alwakeaExes.add(new AlwakeaEx("وفرشٍ مرفوعة على السرر."));
        alwakeaExes.add(new AlwakeaEx("إِنَّا أَنْشَأْنَاهُنَّ إِنْشَاءً (35)"));
        alwakeaExes.add(new AlwakeaEx("إنا أنشأنا نساء أهل الجنة نشأة غير النشأة التي كانت في الدنيا، نشأة كاملة لا تقبل الفناء."));
        alwakeaExes.add(new AlwakeaEx("فَجَعَلْنَاهُنَّ أَبْكَارًا (36)"));
        alwakeaExes.add(new AlwakeaEx("فجعلناهن أبكارًا."));
        alwakeaExes.add(new AlwakeaEx("عُرُبًا أَتْرَابًا (37)"));
        alwakeaExes.add(new AlwakeaEx("متحببات إلى أزواجهن، في سنٍّ واحدة."));
        alwakeaExes.add(new AlwakeaEx("لِأَصْحَابِ الْيَمِينِ (38)"));
        alwakeaExes.add(new AlwakeaEx("خلقناهن لأصحاب اليمين."));
        alwakeaExes.add(new AlwakeaEx("ثُلَّةٌ مِنَ الْأَوَّلِينَ (39)"));
        alwakeaExes.add(new AlwakeaEx("وهم جماعة كثيرة من الأولين."));
        alwakeaExes.add(new AlwakeaEx("وَثُلَّةٌ مِنَ الْآخِرِينَ (40)"));
        alwakeaExes.add(new AlwakeaEx("وجماعة كثيرة من الآخرين."));
        alwakeaExes.add(new AlwakeaEx("وَأَصْحَابُ الشِّمَالِ مَا أَصْحَابُ الشِّمَالِ (41)"));
        alwakeaExes.add(new AlwakeaEx("وأصحاب الشمال ما أسوأ حالهم جزاءهم!!"));
        alwakeaExes.add(new AlwakeaEx("فِي سَمُومٍ وَحَمِيمٍ (42)"));
        alwakeaExes.add(new AlwakeaEx("في ريح حارة من حَرِّ نار جهنم تأخذ بأنفاسهم، وماء حار يغلي."));
        alwakeaExes.add(new AlwakeaEx("وَظِلٍّ مِنْ يَحْمُومٍ (43)"));
        alwakeaExes.add(new AlwakeaEx("وظلٍّ من دخان شديد السواد."));
        alwakeaExes.add(new AlwakeaEx("لَا بَارِدٍ وَلَا كَرِيمٍ (44)"));
        alwakeaExes.add(new AlwakeaEx("لا بارد المنزل، ولا كريم المنظر."));
        alwakeaExes.add(new AlwakeaEx("إِنَّهُمْ كَانُوا قَبْلَ ذَلِكَ مُتْرَفِينَ (45)"));
        alwakeaExes.add(new AlwakeaEx("إنهم كانوا في الدنيا متنعِّمين بالحرام، معرِضين عما جاءتهم به الرسل."));
        alwakeaExes.add(new AlwakeaEx("وَكَانُوا يُصِرُّونَ عَلَى الْحِنْثِ الْعَظِيمِ (46)"));
        alwakeaExes.add(new AlwakeaEx("وكانوا يقيمون على الكفر بالله والإشراك به ومعصيته، ولا ينوون التوبة من ذلك."));
        alwakeaExes.add(new AlwakeaEx("وَكَانُوا يَقُولُونَ أَئِذَا مِتْنَا وَكُنَّا تُرَابًا وَعِظَامًا أَإِنَّا لَمَبْعُوثُونَ (47)"));
        alwakeaExes.add(new AlwakeaEx("وكانوا يقولون إنكارًا للبعث: أنُبعث إذا متنا وصرنا ترابًا وعظامًا بالية؟ وهذا استبعاد منهم لأمر البعث وتكذيب له."));
        alwakeaExes.add(new AlwakeaEx("أَوَآبَاؤُنَا الْأَوَّلُونَ (48)"));
        alwakeaExes.add(new AlwakeaEx("أنُبعث نحن وآبناؤنا الأقدمون الذين صاروا ترابًا، قد تفرَّق في الأرض؟"));
        alwakeaExes.add(new AlwakeaEx("قُلْ إِنَّ الْأَوَّلِينَ وَالْآخِرِينَ (49)"));
        alwakeaExes.add(new AlwakeaEx("قل لهم -أيها الرسول-: إن الأولين والآخرين من بني آدم."));
        alwakeaExes.add(new AlwakeaEx("لَمَجْمُوعُونَ إِلَى مِيقَاتِ يَوْمٍ مَعْلُومٍ (50)"));
        alwakeaExes.add(new AlwakeaEx("سيُجمَعون في يوم مؤقت بوقت محدد، وهو يوم القيامة."));
        alwakeaExes.add(new AlwakeaEx("ثُمَّ إِنَّكُمْ أَيُّهَا الضَّالُّونَ الْمُكَذِّبُونَ (51)"));
        alwakeaExes.add(new AlwakeaEx("ثم إنكم أيها الضالون عن طريق الهدى المكذبون بوعيد الله ووعده."));
        alwakeaExes.add(new AlwakeaEx("لَآكِلُونَ مِنْ شَجَرٍ مِنْ زَقُّومٍ (52)"));
        alwakeaExes.add(new AlwakeaEx("لآكلون من شجر من زقوم، وهو من أقبح الشجر."));
        alwakeaExes.add(new AlwakeaEx("فَمَالِئُونَ مِنْهَا الْبُطُونَ (53)"));
        alwakeaExes.add(new AlwakeaEx("فمالئون منها بطونكم ; لشدة الجوع."));
        alwakeaExes.add(new AlwakeaEx("فَشَارِبُونَ عَلَيْهِ مِنَ الْحَمِيمِ (54)"));
        alwakeaExes.add(new AlwakeaEx("فشاربون عليه ماء متناهيًا في الحرارة لا يَرْوي ظمأ."));
        alwakeaExes.add(new AlwakeaEx("فَشَارِبُونَ شُرْبَ الْهِيمِ (55)"));
        alwakeaExes.add(new AlwakeaEx("فشاربون منه بكثرة، كشرب الإبل العطاش التي لا تَرْوى لداء يصيبها."));
        alwakeaExes.add(new AlwakeaEx("هَذَا نُزُلُهُمْ يَوْمَ الدِّينِ (56)"));
        alwakeaExes.add(new AlwakeaEx("هذا الذي يلقونه من العذاب هو ما أُعدَّ لهم من الزاد يوم القيامة. وفي هذا توبيخ لهم وتهكُّم بهم."));
        alwakeaExes.add(new AlwakeaEx("نَحْنُ خَلَقْنَاكُمْ فَلَوْلَا تُصَدِّقُونَ (57)"));
        alwakeaExes.add(new AlwakeaEx("نحن خلقناكم -أيها الناس- ولم تكونوا شيئًا، فهلا تصدِّقون بالبعث."));
        alwakeaExes.add(new AlwakeaEx("أَفَرَأَيْتُمْ مَا تُمْنُونَ (58)"));
        alwakeaExes.add(new AlwakeaEx("أفرأيتم النُّطَف التي تقذفونها في أرحام نسائكم."));
        alwakeaExes.add(new AlwakeaEx("أَأَنْتُمْ تَخْلُقُونَهُ أَمْ نَحْنُ الْخَالِقُونَ (59)"));
        alwakeaExes.add(new AlwakeaEx("هل أنتم تخلقون ذلك بشرًا أم نحن الخالقون؟"));
        alwakeaExes.add(new AlwakeaEx("نَحْنُ قَدَّرْنَا بَيْنَكُمُ الْمَوْتَ وَمَا نَحْنُ بِمَسْبُوقِينَ (60)"));
        alwakeaExes.add(new AlwakeaEx("نحن قَدَّرنا بينكم الموت، وما نحن بعاجزين."));
        alwakeaExes.add(new AlwakeaEx("عَلَى أَنْ نُبَدِّلَ أَمْثَالَكُمْ وَنُنْشِئَكُمْ فِي مَا لَا تَعْلَمُونَ (61)"));
        alwakeaExes.add(new AlwakeaEx("عن أن نغيِّر خلقكم يوم القيامة، وننشئكم فيما لا تعلمونه من الصفات والأحوال."));
        alwakeaExes.add(new AlwakeaEx("وَلَقَدْ عَلِمْتُمُ النَّشْأَةَ الْأُولَى فَلَوْلَا تَذَكَّرُونَ (62)"));
        alwakeaExes.add(new AlwakeaEx("ولقد علمتم أن الله أنشأكم النشأة الأولى ولم تكونوا شيئًا، فهلا تذكَّرون قدرة الله على إنشائكم مرة أخرى."));
        alwakeaExes.add(new AlwakeaEx("أَفَرَأَيْتُمْ مَا تَحْرُثُونَ (63)"));
        alwakeaExes.add(new AlwakeaEx("أفرأيتم الحرث الذي تحرثونه."));
        alwakeaExes.add(new AlwakeaEx("أَأَنْتُمْ تَزْرَعُونَهُ أَمْ نَحْنُ الزَّارِعُونَ (64)"));
        alwakeaExes.add(new AlwakeaEx("هل أنتم تُنبتونه في الأرض؟ بل نحن نُقِرُّ قراره وننبته في الأرض؟"));
        alwakeaExes.add(new AlwakeaEx(") لَوْ نَشَاءُ لَجَعَلْنَاهُ حُطَامًا فَظَلْتُمْ تَفَكَّهُونَ (65)"));
        alwakeaExes.add(new AlwakeaEx("لو نشاء لجعلنا ذلك الزرع هشيمًا، لا يُنتفع به في مطعم، فأصبحتم تتعجبون مما نزل بزرعكم."));
        alwakeaExes.add(new AlwakeaEx("إِنَّا لَمُغْرَمُونَ (66)"));
        alwakeaExes.add(new AlwakeaEx("وتقولون: إنا لخاسرون معذَّبون."));
        alwakeaExes.add(new AlwakeaEx("بَلْ نَحْنُ مَحْرُومُونَ (67)"));
        alwakeaExes.add(new AlwakeaEx("بل نحن محرومون من الرزق."));
        alwakeaExes.add(new AlwakeaEx("أَفَرَأَيْتُمُ الْمَاءَ الَّذِي تَشْرَبُونَ (68)"));
        alwakeaExes.add(new AlwakeaEx("أفرأيتم الماء الذي تشربونه لتحْيَوا به."));
        alwakeaExes.add(new AlwakeaEx("أَأَنْتُمْ أَنْزَلْتُمُوهُ مِنَ الْمُزْنِ أَمْ نَحْنُ الْمُنْزِلُونَ (69)"));
        alwakeaExes.add(new AlwakeaEx("أأنتم أنزلتموه من السحاب إلى قرار الأرض، أم نحن الذين أنزلناه رحمة بكم؟"));
        alwakeaExes.add(new AlwakeaEx("لَوْ نَشَاءُ جَعَلْنَاهُ أُجَاجًا فَلَوْلَا تَشْكُرُونَ (70)"));
        alwakeaExes.add(new AlwakeaEx("لو نشاء جعلنا هذا الماء شديد الملوحة، لا يُنتفع به في شرب ولا زرع، فهلا تشكرون ربكم على إنزال الماء العذب لنفعكم."));
        alwakeaExes.add(new AlwakeaEx("أَفَرَأَيْتُمُ النَّارَ الَّتِي تُورُونَ (71)"));
        alwakeaExes.add(new AlwakeaEx("أفرأيتم النار التي توقدون."));
        alwakeaExes.add(new AlwakeaEx("أَأَنْتُمْ أَنْشَأْتُمْ شَجَرَتَهَا أَمْ نَحْنُ الْمُنْشِئُونَ (72)"));
        alwakeaExes.add(new AlwakeaEx("أأنتم أوجدتم شجرتها التي تقدح منها النار، أم نحن الموجدون لها؟"));
        alwakeaExes.add(new AlwakeaEx("نَحْنُ جَعَلْنَاهَا تَذْكِرَةً وَمَتَاعًا لِلْمُقْوِينَ (73)"));
        alwakeaExes.add(new AlwakeaEx("نحن جعلنا ناركم التي توقدون تذكيرًا لكم بنار جهنم ومنفعة للمسافرين."));
        alwakeaExes.add(new AlwakeaEx("فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيمِ (74)"));
        alwakeaExes.add(new AlwakeaEx("فنزِّه -أيها النبي- ربك العظيم كامل الأسماء والصفات، كثير الإحسان والخيرات."));
        alwakeaExes.add(new AlwakeaEx("فَلَا أُقْسِمُ بِمَوَاقِعِ النُّجُومِ (75)"));
        alwakeaExes.add(new AlwakeaEx("أقسم الله تعالى بمساقط النجوم في مغاربها في السماء."));
        alwakeaExes.add(new AlwakeaEx("وَإِنَّهُ لَقَسَمٌ لَوْ تَعْلَمُونَ عَظِيمٌ (76)"));
        alwakeaExes.add(new AlwakeaEx("وإنه لَقَسم لو تعلمون قَدَره عظيم."));
        alwakeaExes.add(new AlwakeaEx("إِنَّهُ لَقُرْآنٌ كَرِيمٌ (77)"));
        alwakeaExes.add(new AlwakeaEx("إن هذا القرآن الذي نزل على محمد لقرآن عظيم المنافع، كثير الخير، غزير العلم."));
        alwakeaExes.add(new AlwakeaEx("فِي كِتَابٍ مَكْنُونٍ (78)"));
        alwakeaExes.add(new AlwakeaEx("في كتاب مَصُون مستور عن أعين الخلق، وهو الكتاب الذي بأيدي الملائكة."));
        alwakeaExes.add(new AlwakeaEx("لَا يَمَسُّهُ إِلَّا الْمُطَهَّرُونَ (79)"));
        alwakeaExes.add(new AlwakeaEx("لا يَمَسُّ القرآن إلا الملائكة الكرام الذين طهرهم الله من الآفات والذنوب، ولا يَمَسُّه أيضًا إلا المتطهرون من الشرك والجنابة والحدث."));
        alwakeaExes.add(new AlwakeaEx("تَنْزِيلٌ مِنْ رَبِّ الْعَالَمِينَ (80)"));
        alwakeaExes.add(new AlwakeaEx("وهذا القرآن الكريم منزل من رب العالمين، فهو الحق الذي لا مرية فيه."));
        alwakeaExes.add(new AlwakeaEx("أَفَبِهَذَا الْحَدِيثِ أَنْتُمْ مُدْهِنُونَ (81)"));
        alwakeaExes.add(new AlwakeaEx("أفبهذا القرآن أنتم -أيها المشركون- مكذِّبون؟"));
        alwakeaExes.add(new AlwakeaEx("وَتَجْعَلُونَ رِزْقَكُمْ أَنَّكُمْ تُكَذِّبُونَ (82)"));
        alwakeaExes.add(new AlwakeaEx("وتجعلون شكركم لنعم الله عليكم أنكم تكذِّبون بها وتكفرون؟\n" +
                "وفي هذا إنكار على من يتهاون بأمر القرآن ولا يبالي بدعوته.\n"));
        alwakeaExes.add(new AlwakeaEx(""));
        alwakeaExes.add(new AlwakeaEx("فَلَوْلَا إِذَا بَلَغَتِ الْحُلْقُومَ (83)"));
        alwakeaExes.add(new AlwakeaEx("فهل تستطيعون إذا بلغت نفس أحدكم الحلقوم عند النزع."));
        alwakeaExes.add(new AlwakeaEx("وَأَنْتُمْ حِينَئِذٍ تَنْظُرُونَ (84)"));
        alwakeaExes.add(new AlwakeaEx("تم حضور تنظرون إليه، أن تمسكوا روحه في جسده؟ لن تستطيعوا ذلك."));
        alwakeaExes.add(new AlwakeaEx("وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْكُمْ وَلَكِنْ لَا تُبْصِرُونَ (85)"));
        alwakeaExes.add(new AlwakeaEx("ونحن أقرب إليه منكم بملائكتنا، ولكنكم لا ترونهم."));
        alwakeaExes.add(new AlwakeaEx("فَلَوْلَا إِنْ كُنْتُمْ غَيْرَ مَدِينِينَ (86)"));
        alwakeaExes.add(new AlwakeaEx("وهل تستطيعون إن كنتم غير محاسبين ولا مجزيين بأعمالكم."));
        alwakeaExes.add(new AlwakeaEx("تَرْجِعُونَهَا إِنْ كُنْتُمْ صَادِقِينَ (87)"));
        alwakeaExes.add(new AlwakeaEx("أن تعيدوا الروح إلى الجسد، إن كنتم صادقين؟ لن ترجعوها."));
        alwakeaExes.add(new AlwakeaEx("فَأَمَّا إِنْ كَانَ مِنَ الْمُقَرَّبِينَ (88)"));
        alwakeaExes.add(new AlwakeaEx("فأما إن كان الميت من السابقين المقربين."));
        alwakeaExes.add(new AlwakeaEx("فَرَوْحٌ وَرَيْحَانٌ وَجَنَّتُ نَعِيمٍ (89)"));
        alwakeaExes.add(new AlwakeaEx("فله عند موته الرحمة الواسعة والفرح وما تطيب به نفسه، وله جنة النعيم في الآخرة."));
        alwakeaExes.add(new AlwakeaEx("وَأَمَّا إِنْ كَانَ مِنْ أَصْحَابِ الْيَمِينِ (90)"));
        alwakeaExes.add(new AlwakeaEx("وأما إن كان الميت من أصحاب اليمين."));
        alwakeaExes.add(new AlwakeaEx("فَسَلَامٌ لَكَ مِنْ أَصْحَابِ الْيَمِينِ (91)"));
        alwakeaExes.add(new AlwakeaEx("فيقال له: سلامة لك وأمن; لكونك من أصحاب اليمين."));
        alwakeaExes.add(new AlwakeaEx("وَأَمَّا إِنْ كَانَ مِنَ الْمُكَذِّبِينَ الضَّالِّينَ (92)"));
        alwakeaExes.add(new AlwakeaEx("وأما إن كان الميت من المكذبين بالبعث، الضالين عن الهدى."));
        alwakeaExes.add(new AlwakeaEx("فَنُزُلٌ مِنْ حَمِيمٍ (93)"));
        alwakeaExes.add(new AlwakeaEx("فله ضيافة من شراب جهنم المغلي المتناهي الحرارة."));
        alwakeaExes.add(new AlwakeaEx("وَتَصْلِيَةُ جَحِيمٍ (94)"));
        alwakeaExes.add(new AlwakeaEx("والنار يحرق بها، ويقاسي عذابها الشديد."));
        alwakeaExes.add(new AlwakeaEx("إِنَّ هَذَا لَهُوَ حَقُّ الْيَقِينِ (95)"));
        alwakeaExes.add(new AlwakeaEx("إن هذا الذي قصصناه عليك -أيها الرسول- لهو حق اليقين الذي لا مرية فيه."));
        alwakeaExes.add(new AlwakeaEx("فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيمِ (96)"));
        alwakeaExes.add(new AlwakeaEx("فسبِّح باسم ربك العظيم، ونزِّهه عما يقول الظالمون والجاحدون، تعالى الله عما يقولون علوًا كبيرًا."));


        quran_explanation_56_adapter = new quran_explanation_56_adapter(alwakeaExes ,QuranExplanation_56Activity.this);

        recyclerView = findViewById(R.id.rv_explanation_56);
        recyclerView.setLayoutManager(new LinearLayoutManager(QuranExplanation_56Activity.this));
        recyclerView.setAdapter(quran_explanation_56_adapter);


    }

}