package com.example.muslim;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;

public class QuranExplanation_26Activity extends AppCompatActivity {

    ArrayList<AlshoaraaEx> alshoaraaExes = new ArrayList<>();
    RecyclerView recyclerView;
    quran_explanation_26_adapter quran_explanation_26_adapter;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_quran_explanation_26);

        alshoaraaExes.add(new AlshoaraaEx("بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ"));
        alshoaraaExes.add(new AlshoaraaEx("طسم (1)"));
        alshoaraaExes.add(new AlshoaraaEx("(طسم) سبق الكلام على الحروف المقطعة في أول سورة البقرة."));
        alshoaraaExes.add(new AlshoaraaEx("تِلْكَ آيَاتُ الْكِتَابِ الْمُبِينِ (2)"));
        alshoaraaExes.add(new AlshoaraaEx("هذه آيات القرآن الموضِّح لكل شيء الفاصل بين الهدى والضلال."));
        alshoaraaExes.add(new AlshoaraaEx("لَعَلَّكَ بَاخِعٌ نَفْسَكَ أَلَّا يَكُونُوا مُؤْمِنِينَ (3)"));
        alshoaraaExes.add(new AlshoaraaEx("لعلك - أيها الرسول - من شدة حرصك على هدايتهم مُهْلِك نفسك؛ لأنهم لم يصدِّقوا بك ولم يعملوا بهديك، فلا تفعل ذلك."));
        alshoaraaExes.add(new AlshoaraaEx("إِنْ نَشَأْ نُنَزِّلْ عَلَيْهِمْ مِنَ السَّمَاءِ آيَةً فَظَلَّتْ أَعْنَاقُهُمْ لَهَا خَاضِعِينَ (4)"));
        alshoaraaExes.add(new AlshoaraaEx("إن نشأ ننزل على المكذبين من قومك من السماء معجزة مخوِّفة لهم تلجئهم إلى الإيمان، فتصير أعناقهم خاضعة ذليلة، ولكننا لم نشأ ذلك; فإن الإيمان النافع هو الإيمان بالغيب اختيارًا."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا يَأْتِيهِمْ مِنْ ذِكْرٍ مِنَ الرَّحْمَنِ مُحْدَثٍ إِلَّا كَانُوا عَنْهُ مُعْرِضِينَ (5)"));
        alshoaraaExes.add(new AlshoaraaEx("وما يجيء هؤلاء المشركين المكذبين مِن ذِكْرٍ من الرحمن مُحْدَث إنزاله، شيئًا بعد شيء، يأمرهم وينهاهم، ويذكرهم بالدين الحق إلا أعرضوا عنه، ولم يقبلوه."));
        alshoaraaExes.add(new AlshoaraaEx("فَقَدْ كَذَّبُوا فَسَيَأْتِيهِمْ أَنْبَاءُ مَا كَانُوا بِهِ يَسْتَهْزِئُونَ (6)"));
        alshoaraaExes.add(new AlshoaraaEx("فقد كذَّبوا بالقرآن واستهزؤوا به، فسيأتيهم أخبار الأمر الذي كانوا يستهزئون به ويسخرون منه، وسيحلُّ بهم العذاب جزاء تمردهم على ربهم."));
        alshoaraaExes.add(new AlshoaraaEx("أَوَلَمْ يَرَوْا إِلَى الْأَرْضِ كَمْ أَنْبَتْنَا فِيهَا مِنْ كُلِّ زَوْجٍ كَرِيمٍ (7)"));
        alshoaraaExes.add(new AlshoaraaEx("أكذبوا ولم ينظروا إلى الأرض التي أنبتنا فيها من كل نوع حسن نافع من النبات، لا يقدر على إنباته إلا رب العالمين؟"));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّ فِي ذَلِكَ لَآيَةً وَمَا كَانَ أَكْثَرُهُمْ مُؤْمِنِينَ (8)"));
        alshoaraaExes.add(new AlshoaraaEx("إن في إخراج النبات من الأرض لَدلالة واضحة على كمال قدرة الله، وما كان أكثر القوم مؤمنين."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ (9)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن ربك لهو العزيز على كل مخلوق، الرحيم الذي وسعت رحمته كل شيء."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِذْ نَادَى رَبُّكَ مُوسَى أَنِ ائْتِ الْقَوْمَ الظَّالِمِينَ (10)"));
        alshoaraaExes.add(new AlshoaraaEx("واذكر - أيها الرسول - لقومك إذ نادى ربك موسى: أن ائت القوم الظالمين."));
        alshoaraaExes.add(new AlshoaraaEx("قَوْمَ فِرْعَوْنَ أَلَا يَتَّقُونَ (11)"));
        alshoaraaExes.add(new AlshoaraaEx("قوم فرعون، وقل لهم: ألا يخافون عقاب الله تعالى، ويتركون ما هم عليه من الكفر والضلال؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ رَبِّ إِنِّي أَخَافُ أَنْ يُكَذِّبُونِ (12)"));
        alshoaraaExes.add(new AlshoaraaEx("قال موسى: رب إني أخاف أن يكذبوني في الرسالة، ويملأ صدري الغمُّ لتكذيبهم إياي."));
        alshoaraaExes.add(new AlshoaraaEx("وَيَضِيقُ صَدْرِي وَلَا يَنْطَلِقُ لِسَانِي فَأَرْسِلْ إِلَى هَارُونَ (13)"));
        alshoaraaExes.add(new AlshoaraaEx("ولا ينطلق لساني بالدعوة فأرسِلْ جبريل بالوحي إلى أخي هارون؛ ليعاونني ويصدقني فيما أقول، ويبين لهم ما أخاطبهم به، فهو أفصح مني نطقاً."));
        alshoaraaExes.add(new AlshoaraaEx("وَلَهُمْ عَلَيَّ ذَنْبٌ فَأَخَافُ أَنْ يَقْتُلُونِ (14)"));
        alshoaraaExes.add(new AlshoaraaEx("ولهم علي ذنب في قتل رجل منهم، وهو القبطي، فأخاف أن يقتلوني به."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ كَلَّا فَاذْهَبَا بِآيَاتِنَا إِنَّا مَعَكُمْ مُسْتَمِعُونَ (15)"));
        alshoaraaExes.add(new AlshoaraaEx("قال الله لموسى: كلا لن يقتلوك، وقد أجبت طلبك في هارون، فاذهبا بالمعجزات الدالة على صدقكما، إنا معكم بالعلم والحفظ والنصرة مستمعون."));
        alshoaraaExes.add(new AlshoaraaEx("فَأْتِيَا فِرْعَوْنَ فَقُولَا إِنَّا رَسُولُ رَبِّ الْعَالَمِينَ (16)"));
        alshoaraaExes.add(new AlshoaraaEx("فأتِيَا فرعون فقولا له: إنا مرسَلان إليك وإلى قومك من رب العالمين."));
        alshoaraaExes.add(new AlshoaraaEx("أَنْ أَرْسِلْ مَعَنَا بَنِي إِسْرَائِيلَ (17)"));
        alshoaraaExes.add(new AlshoaraaEx("أن اترك بني إسرائيل؛ ليذهبوا معنا."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ أَلَمْ نُرَبِّكَ فِينَا وَلِيدًا وَلَبِثْتَ فِينَا مِنْ عُمُرِكَ سِنِينَ (18)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون لموسى -ممتنًا عليه-: ألم نُرَبِّك في منازلنا صغيرًا، ومكثت في رعايتنا سنين من عُمُرك."));
        alshoaraaExes.add(new AlshoaraaEx("وَفَعَلْتَ فَعْلَتَكَ الَّتِي فَعَلْتَ وَأَنْتَ مِنَ الْكَافِرِينَ (19)"));
        alshoaraaExes.add(new AlshoaraaEx("وارتكبت جنايةً بقتلك رجلا من قومي حين ضربته ودفعته، وأنت من الجاحدين نعمتي المنكرين ربوبيتي؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ فَعَلْتُهَا إِذًا وَأَنَا مِنَ الضَّالِّينَ (20)"));
        alshoaraaExes.add(new AlshoaraaEx("قال موسى مجيبًا لفرعون: فعلتُ ما ذكرتَ قبل أن يوحي الله إلي، ويبعثني رسولا."));
        alshoaraaExes.add(new AlshoaraaEx("فَفَرَرْتُ مِنْكُمْ لَمَّا خِفْتُكُمْ فَوَهَبَ لِي رَبِّي حُكْمًا وَجَعَلَنِي مِنَ الْمُرْسَلِينَ (21)"));
        alshoaraaExes.add(new AlshoaraaEx("فخرجت من بينكم فارًّا إلى «مدين» ، لمَّا خفت أن تقتلوني بما فعلتُ من غير عَمْد، فوهب لي ربي تفضلا منه النبوة والعلم، وجعلني من المرسلين."));
        alshoaraaExes.add(new AlshoaraaEx("وَتِلْكَ نِعْمَةٌ تَمُنُّهَا عَلَيَّ أَنْ عَبَّدْتَ بَنِي إِسْرَائِيلَ (22)"));
        alshoaraaExes.add(new AlshoaraaEx("أو تلك التربية في بيتك تَعُدُّها نعمة منك عليَّ، وقد جعلت بني إسرائيل عبيدًا تذبح أبناءهم وتستبقي نساءهم للخدمة والامتهان؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ فِرْعَوْنُ وَمَا رَبُّ الْعَالَمِينَ (23)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون لموسى: وما رب العالمين الذي تدَّعي أنك رسوله؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ رَبُّ السَّمَاوَاتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا إِنْ كُنْتُمْ مُوقِنِينَ (24)"));
        alshoaraaExes.add(new AlshoaraaEx("قال موسى: هو مالك ومدبر السموات والأرض وما بينهما، إن كنتم موقنين بذلك، فآمِنوا."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ لِمَنْ حَوْلَهُ أَلَا تَسْتَمِعُونَ (25)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون لمن حوله مِن أشراف قومه: ألا تسمعون مقالة موسى العجيبة بوجود رب سواي؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ رَبُّكُمْ وَرَبُّ آبَائِكُمُ الْأَوَّلِينَ (26)"));
        alshoaraaExes.add(new AlshoaraaEx("قال موسى: الرب الذي أدعوكم إليه هو الذي خلقكم وخلق آباءكم الأولين، فكيف تعبدون مَن هو مخلوق مثلكم، وله آباء قد فنوا كآبائكم؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ إِنَّ رَسُولَكُمُ الَّذِي أُرْسِلَ إِلَيْكُمْ لَمَجْنُونٌ (27)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون لخاصته يستثير غضبهم؛ لتكذيب موسى إياه: إن رسولكم الذي أرسل إليكم لمجنون، يتكلم كلامًا لا يُعْقَل!"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ رَبُّ الْمَشْرِقِ وَالْمَغْرِبِ وَمَا بَيْنَهُمَا إِنْ كُنْتُمْ تَعْقِلُونَ (28)"));
        alshoaraaExes.add(new AlshoaraaEx("قال موسى: رب المشرق والمغرب وما بينهما وما يكون فيهما من نور وظلمة، وهذا يستوجب الإيمان به وحده إن كنتم من أهل العقل والتدبر!"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ لَئِنِ اتَّخَذْتَ إِلَهًا غَيْرِي لَأَجْعَلَنَّكَ مِنَ الْمَسْجُونِينَ (29)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون لموسى مهددًا له: لئن اتخذت إلهًا غيري لأسجننك مع مَن سجنت."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ أَوَلَوْ جِئْتُكَ بِشَيْءٍ مُبِينٍ (30)"));
        alshoaraaExes.add(new AlshoaraaEx("قال موسى: أتجعلني من المسجونين، ولو جئتك ببرهان قاطع يتبين منه صدقي؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ فَأْتِ بِهِ إِنْ كُنْتَ مِنَ الصَّادِقِينَ (31)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون: فأت به إن كنت من الصادقين في دعواك."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَلْقَى عَصَاهُ فَإِذَا هِيَ ثُعْبَانٌ مُبِينٌ (32)"));
        alshoaraaExes.add(new AlshoaraaEx("فألقى موسى عصاه فتحولت ثعبانًا حقيقيًا، ليس تمويهًا كما يفعل السحرة."));
        alshoaraaExes.add(new AlshoaraaEx("وَنَزَعَ يَدَهُ فَإِذَا هِيَ بَيْضَاءُ لِلنَّاظِرِينَ (33)"));
        alshoaraaExes.add(new AlshoaraaEx("وأخرج يده مِن جيبه فإذا هي بيضاء كالثلج من غير برص، تَبْهَر الناظرين."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ لِلْمَلَإِ حَوْلَهُ إِنَّ هَذَا لَسَاحِرٌ عَلِيمٌ (34)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون لأشراف قومه خشية أن يؤمنوا: إن موسى لَساحر ماهر."));
        alshoaraaExes.add(new AlshoaraaEx("يُرِيدُ أَنْ يُخْرِجَكُمْ مِنْ أَرْضِكُمْ بِسِحْرِهِ فَمَاذَا تَأْمُرُونَ (35)"));
        alshoaraaExes.add(new AlshoaraaEx("يريد أن يخرجكم بسحره من أرضكم، فأي شيء تشيرون به في شأنه أتبع رأيكم فيه؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا أَرْجِهْ وَأَخَاهُ وَابْعَثْ فِي الْمَدَائِنِ حَاشِرِينَ (36)"));
        alshoaraaExes.add(new AlshoaraaEx("قال له قومه: أخِّر أمر موسى وهارون، وأرسِلْ في المدائن جندًا جامعين للسحرة."));
        alshoaraaExes.add(new AlshoaraaEx("يَأْتُوكَ بِكُلِّ سَحَّارٍ عَلِيمٍ (37)"));
        alshoaraaExes.add(new AlshoaraaEx("يأتوك بكلِّ مَن أجاد السحر، وتفوَّق في معرفته."));
        alshoaraaExes.add(new AlshoaraaEx("فَجُمِعَ السَّحَرَةُ لِمِيقَاتِ يَوْمٍ مَعْلُومٍ (38)"));
        alshoaraaExes.add(new AlshoaraaEx("فَجُمع السحرة، وحُدِّد لهم وقت معلوم، هو وقت الضحى من يوم الزينة الذي يتفرغون فيه من أشغالهم، ويجتمعون ويتزيَّنون؛ وذلك للاجتماع بموسى."));
        alshoaraaExes.add(new AlshoaraaEx("وَقِيلَ لِلنَّاسِ هَلْ أَنْتُمْ مُجْتَمِعُونَ (39)"));
        alshoaraaExes.add(new AlshoaraaEx("وحُثَّ الناس على الاجتماع; أملا في أن تكون الغلبة للسحرة."));
        alshoaraaExes.add(new AlshoaraaEx("لَعَلَّنَا نَتَّبِعُ السَّحَرَةَ إِنْ كَانُوا هُمُ الْغَالِبِينَ (40)"));
        alshoaraaExes.add(new AlshoaraaEx("إننا نطمع أن تكون الغلبة للسحرة، فنثبت على ديننا."));
        alshoaraaExes.add(new AlshoaraaEx("فَلَمَّا جَاءَ السَّحَرَةُ قَالُوا لِفِرْعَوْنَ أَئِنَّ لَنَا لَأَجْرًا إِنْ كُنَّا نَحْنُ الْغَالِبِينَ (41)"));
        alshoaraaExes.add(new AlshoaraaEx("فلما جاء السحرة فرعون قالوا له: أإن لنا لأجرًا مِن مال أو جاه، إنْ كنا نحن الغالبين لموسى؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ نَعَمْ وَإِنَّكُمْ إِذًا لَمِنَ الْمُقَرَّبِينَ (42)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون: نعم لكم عندي ما طلبتم مِن أجر، وإنكم حينئذ لمن المقربين لديَّ."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ لَهُمْ مُوسَى أَلْقُوا مَا أَنْتُمْ مُلْقُونَ (43)"));
        alshoaraaExes.add(new AlshoaraaEx("قال موسى للسحرة مريدًا إبطال سحرهم وإظهار أن ما جاء به ليس سحرًا: ألقوا ما تريدون إلقاءه من السحر."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَلْقَوْا حِبَالَهُمْ وَعِصِيَّهُمْ وَقَالُوا بِعِزَّةِ فِرْعَوْنَ إِنَّا لَنَحْنُ الْغَالِبُونَ (44)"));
        alshoaraaExes.add(new AlshoaraaEx("فألقَوا حبالهم وعصيَّهم، وخُيِّل للناس أنها حيَّات تسعى، وأقسموا بعزة فرعون قائلين: إننا لنحن الغالبون."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَلْقَى مُوسَى عَصَاهُ فَإِذَا هِيَ تَلْقَفُ مَا يَأْفِكُونَ (45)"));
        alshoaraaExes.add(new AlshoaraaEx("فألقى موسى عصاه، فإذا هي حية عظيمة، تبتلع ما صدر منهم من إفك وتزوير."));
        alshoaraaExes.add(new AlshoaraaEx("فَأُلْقِيَ السَّحَرَةُ سَاجِدِينَ (46)"));
        alshoaraaExes.add(new AlshoaraaEx("فلما شاهدوا ذلك، وعلموا أنه ليس من تمويه السحرة، آمنوا بالله وسجدوا له."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا آمَنَّا بِرَبِّ الْعَالَمِينَ (47)"));
        alshoaraaExes.add(new AlshoaraaEx("وقالوا: آمنَّا برب العالمين."));
        alshoaraaExes.add(new AlshoaraaEx("رَبِّ مُوسَى وَهَارُونَ (48)"));
        alshoaraaExes.add(new AlshoaraaEx("رب موسى وهارون."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ آمَنْتُمْ لَهُ قَبْلَ أَنْ آذَنَ لَكُمْ إِنَّهُ لَكَبِيرُكُمُ الَّذِي عَلَّمَكُمُ السِّحْرَ فَلَسَوْفَ تَعْلَمُونَ لَأُقَطِّعَنَّ أَيْدِيَكُمْ وَأَرْجُلَكُمْ مِنْ خِلَافٍ وَلَأُصَلِّبَنَّكُمْ أَجْمَعِينَ (49)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون للسحرة مستنكرًا: آمنتم لموسى بغير إذن مني، وقال موهمًا أنَّ فِعْل موسى سحر: إنه لكبيركم الذي علَّمكم السحر، فلسوف تعلمون ما ينزل بكم من عقاب: لأقطعنَّ أيديكم وأرجلكم من خلاف: بقطع اليد اليمنى والرجل اليسرى أو عكس ذلك، ولأصلبنَّكم أجمعين."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا لَا ضَيْرَ إِنَّا إِلَى رَبِّنَا مُنْقَلِبُونَ (50)"));
        alshoaraaExes.add(new AlshoaraaEx("قال السحرة لفرعون: لا ضرر علينا فيما يلحقنا من عقاب الدنيا، إنا راجعون إلى ربنا فيعطينا النعيم المقيم."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّا نَطْمَعُ أَنْ يَغْفِرَ لَنَا رَبُّنَا خَطَايَانَا أَنْ كُنَّا أَوَّلَ الْمُؤْمِنِينَ (51)"));
        alshoaraaExes.add(new AlshoaraaEx("إنا نرجو أن يغفر لنا ربنا خطايانا من الشرك وغيره; لكوننا أول المؤمنين في قومك."));
        alshoaraaExes.add(new AlshoaraaEx("وَأَوْحَيْنَا إِلَى مُوسَى أَنْ أَسْرِ بِعِبَادِي إِنَّكُمْ مُتَّبَعُونَ (52)"));
        alshoaraaExes.add(new AlshoaraaEx("وأوحى الله إلى موسى عليه السلام: أَنْ سِرْ ليلا بمن آمن من بني إسرائيل؛ لأن فرعون وجنوده متبعوكم حتى لا يدركوكم قبل وصولكم إلى البحر."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَرْسَلَ فِرْعَوْنُ فِي الْمَدَائِنِ حَاشِرِينَ (53)"));
        alshoaraaExes.add(new AlshoaraaEx("فأرسل فرعون جنده -حين بلغه مسير بني إسرائيل- يجمعون جيشه من مدائن مملكته."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّ هَؤُلَاءِ لَشِرْذِمَةٌ قَلِيلُونَ (54)"));
        alshoaraaExes.add(new AlshoaraaEx("قال فرعون: إن بني إسرائيل الذين فرُّوا مع موسى لَطائفة حقيرة قليلة العدد."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّهُمْ لَنَا لَغَائِظُونَ (55)"));
        alshoaraaExes.add(new AlshoaraaEx("وإنهم لمالئون صدورنا غيظًا؛ حيث خالفوا ديننا، وخرجوا بغير إذننا."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّا لَجَمِيعٌ حَاذِرُونَ (56)"));
        alshoaraaExes.add(new AlshoaraaEx("وإنا لجميع متيقظون مستعدون لهم."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَخْرَجْنَاهُمْ مِنْ جَنَّاتٍ وَعُيُونٍ (57)"));
        alshoaraaExes.add(new AlshoaraaEx("فأخرج الله فرعون وقومه من أرض «مصر» ذات البساتين وعيون الماء."));
        alshoaraaExes.add(new AlshoaraaEx("وَكُنُوزٍ وَمَقَامٍ كَرِيمٍ (58)"));
        alshoaraaExes.add(new AlshoaraaEx("وخزائن المال والمنازل الحسان. وكما أخرجناهم."));
        alshoaraaExes.add(new AlshoaraaEx("كَذَلِكَ وَأَوْرَثْنَاهَا بَنِي إِسْرَائِيلَ (59)"));
        alshoaraaExes.add(new AlshoaraaEx("جعلنا هذه الديار من بعدهم لبني إسرائيل."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَتْبَعُوهُمْ مُشْرِقِينَ (60)"));
        alshoaraaExes.add(new AlshoaraaEx("فلحق فرعون وجنده موسى ومَن معه وقت شروق الشمس."));
        alshoaraaExes.add(new AlshoaraaEx("فَلَمَّا تَرَاءَى الْجَمْعَانِ قَالَ أَصْحَابُ مُوسَى إِنَّا لَمُدْرَكُونَ (61)"));
        alshoaraaExes.add(new AlshoaraaEx("فلما رأى كل واحد من الفريقين الآخر قال أصحاب موسى: إنَّ جَمْعَ فرعون مُدْرِكنا ومهلكنا."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ كَلَّا إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ (62)"));
        alshoaraaExes.add(new AlshoaraaEx("قال موسى لهم: كلا ليس الأمر كما ذكرتم فلن تُدْرَكوا; إن معي ربي بالنصر، سيهديني لما فيه نجاتي ونجاتكم."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَوْحَيْنَا إِلَى مُوسَى أَنِ اضْرِبْ بِعَصَاكَ الْبَحْرَ فَانْفَلَقَ فَكَانَ كُلُّ فِرْقٍ كَالطَّوْدِ الْعَظِيمِ (63)"));
        alshoaraaExes.add(new AlshoaraaEx("فأوحينا إلى موسى أن اضرب بعصاك البحر، فضرب، فانفلق البحر إلى اثني عشر طريقًا بعدد قبائل بني إسرائيل، فكانت كل قطعة انفصلت من البحر كالجبل العظيم."));
        alshoaraaExes.add(new AlshoaraaEx("وَأَزْلَفْنَا ثَمَّ الْآخَرِينَ (64)"));
        alshoaraaExes.add(new AlshoaraaEx("وقرَّبْنا هناك فرعون وقومه حتى دخلوا البحر."));
        alshoaraaExes.add(new AlshoaraaEx("وَأَنْجَيْنَا مُوسَى وَمَنْ مَعَهُ أَجْمَعِينَ (65)"));
        alshoaraaExes.add(new AlshoaraaEx("وأنجينا موسى ومَن معه أجمعين. فاستمر البحر على انفلاقه حتى عبروا إلى البر."));
        alshoaraaExes.add(new AlshoaraaEx("ثُمَّ أَغْرَقْنَا الْآخَرِينَ (66)"));
        alshoaraaExes.add(new AlshoaraaEx("ثم أغرقنا فرعون ومن معه بإطباق البحر عليهم بعد أن دخلوا فيه متبعين موسى وقومه."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّ فِي ذَلِكَ لَآيَةً وَمَا كَانَ أَكْثَرُهُمْ مُؤْمِنِينَ (67)"));
        alshoaraaExes.add(new AlshoaraaEx("إن في ذلك الذي حدث لَعبرة عجيبة دالة على قدرة الله، وما صار أكثر أتباع فرعون مؤمنين مع هذه العلامة الباهرة."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ (68)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن ربك لهو العزيز الرحيم، بعزته أهلك الكافرين المكذبين، وبرحمته نجَّى موسى ومَن معه أجمعين."));
        alshoaraaExes.add(new AlshoaraaEx("وَاتْلُ عَلَيْهِمْ نَبَأَ إِبْرَاهِيمَ (69)"));
        alshoaraaExes.add(new AlshoaraaEx("واقصص على الكافرين - أيها الرسول - خبر إبراهيم."));
        alshoaraaExes.add(new AlshoaraaEx("إِذْ قَالَ لِأَبِيهِ وَقَوْمِهِ مَا تَعْبُدُونَ (70)"));
        alshoaraaExes.add(new AlshoaraaEx("حين قال لأبيه وقومه: أي شيء تعبدونه؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا نَعْبُدُ أَصْنَامًا فَنَظَلُّ لَهَا عَاكِفِينَ (71)"));
        alshoaraaExes.add(new AlshoaraaEx("قالوا: نعبد أصنامًا، فنَعْكُف على عبادتها."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ هَلْ يَسْمَعُونَكُمْ إِذْ تَدْعُونَ (72)"));
        alshoaraaExes.add(new AlshoaraaEx("قال إبراهيم منبهًا على فساد مذهبهم: هل يسمعون دعاءكم إذ تدعونهم."));
        alshoaraaExes.add(new AlshoaraaEx("أَوْ يَنْفَعُونَكُمْ أَوْ يَضُرُّونَ (73)"));
        alshoaraaExes.add(new AlshoaraaEx("أو يقدِّمون لكم نفعًا إذا عبدتموهم، أو يصيبونكم بضر إذا تركتم عبادتهم؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا بَلْ وَجَدْنَا آبَاءَنَا كَذَلِكَ يَفْعَلُونَ (74)"));
        alshoaraaExes.add(new AlshoaraaEx("قالوا: لا يكون منهم شيء من ذلك، ولكننا وجدنا آباءنا يعبدونهم، فقلَّدناهم فيما كانوا يفعلون."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ أَفَرَأَيْتُمْ مَا كُنْتُمْ تَعْبُدُونَ (75)"));
        alshoaraaExes.add(new AlshoaraaEx("قال إبراهيم: أفأبصرتم بتدبر ما كنتم تعبدون من الأصنام التي لا تسمع ولا تنفع ولا تضر."));
        alshoaraaExes.add(new AlshoaraaEx("أَنْتُمْ وَآبَاؤُكُمُ الْأَقْدَمُونَ (76)"));
        alshoaraaExes.add(new AlshoaraaEx("أنتم وآباؤكم الأقدمون من قبلكم؟"));
        alshoaraaExes.add(new AlshoaraaEx("فَإِنَّهُمْ عَدُوٌّ لِي إِلَّا رَبَّ الْعَالَمِينَ (77)"));
        alshoaraaExes.add(new AlshoaraaEx("فإن ما تعبدونهم من دون الله أعداء لي، لكن رب العالمين ومالك أمرهم هو وحده الذي أعبده."));
        alshoaraaExes.add(new AlshoaraaEx("الَّذِي خَلَقَنِي فَهُوَ يَهْدِينِ (78)"));
        alshoaraaExes.add(new AlshoaraaEx("هو الذي خلقني في أحسن صورة فهو يرشدني إلى مصالح الدنيا والآخرة."));
        alshoaraaExes.add(new AlshoaraaEx("وَالَّذِي هُوَ يُطْعِمُنِي وَيَسْقِينِ (79)"));
        alshoaraaExes.add(new AlshoaraaEx("وهو الذي ينعم عليَّ بالطعام والشراب."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ (80)"));
        alshoaraaExes.add(new AlshoaraaEx("وإذا أصابني مرض فهو الذي يَشْفيني ويعافيني منه."));
        alshoaraaExes.add(new AlshoaraaEx("وَالَّذِي يُمِيتُنِي ثُمَّ يُحْيِينِ (81)"));
        alshoaraaExes.add(new AlshoaraaEx("وهو الذي يميتني في الدينا بقبض روحي، ثم يحييني يوم القيامة، لا يقدر على ذلك أحد سواه."));
        alshoaraaExes.add(new AlshoaraaEx("وَالَّذِي أَطْمَعُ أَنْ يَغْفِرَ لِي خَطِيئَتِي يَوْمَ الدِّينِ (82)"));
        alshoaraaExes.add(new AlshoaraaEx("والذي أطمع أن يتجاوز عن ذنبي يوم الجزاء."));
        alshoaraaExes.add(new AlshoaraaEx("رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ (83)"));
        alshoaraaExes.add(new AlshoaraaEx("قال إبراهيم داعيًا ربه: ربِّ امنحني العلم والفهم، وألحقني بالصالحين، واجمع بيني وبينهم في الجنة."));
        alshoaraaExes.add(new AlshoaraaEx("وَاجْعَلْ لِي لِسَانَ صِدْقٍ فِي الْآخِرِينَ (84)"));
        alshoaraaExes.add(new AlshoaraaEx("واجعل لي ثناء حسنًا وذكرًا جميلا في الذين يأتون بعدي إلى يوم القيامة."));
        alshoaraaExes.add(new AlshoaraaEx("وَاجْعَلْنِي مِنْ وَرَثَةِ جَنَّةِ النَّعِيمِ (85)"));
        alshoaraaExes.add(new AlshoaraaEx("واجعلني من عبادك الذين تورثهم نعيم الجنة."));
        alshoaraaExes.add(new AlshoaraaEx("وَاغْفِرْ لِأَبِي إِنَّهُ كَانَ مِنَ الضَّالِّينَ (86)"));
        alshoaraaExes.add(new AlshoaraaEx("وهذا دعاء من إبراهيم عليه السلام أن ينقذ الله أباه من الضلال إلى الهدى، فيغفر له ويتجاوز عنه، كما وعد إبراهيم أباه بالدعاء له، فلما تبيَّن له أنه مستمر في الكفر والشرك إلى أن يموت تبرَّأ منه."));
        alshoaraaExes.add(new AlshoaraaEx("وَلَا تُخْزِنِي يَوْمَ يُبْعَثُونَ (87)"));
        alshoaraaExes.add(new AlshoaraaEx("ولا تُلْحق بي الذل، يوم يخرج الناس من القبور للحساب والجزاء."));
        alshoaraaExes.add(new AlshoaraaEx("يَوْمَ لَا يَنْفَعُ مَالٌ وَلَا بَنُونَ (88)"));
        alshoaraaExes.add(new AlshoaraaEx("يوم لا ينفع المال والبنون أحدًا من العباد."));
        alshoaraaExes.add(new AlshoaraaEx("إِلَّا مَنْ أَتَى اللَّهَ بِقَلْبٍ سَلِيمٍ (89)"));
        alshoaraaExes.add(new AlshoaraaEx("إلا مَن أتى الله بقلب سليم من الكفر والنفاق والرذيلة."));
        alshoaraaExes.add(new AlshoaraaEx("وَأُزْلِفَتِ الْجَنَّةُ لِلْمُتَّقِينَ (90)"));
        alshoaraaExes.add(new AlshoaraaEx("وقُرِّبت الجنة للذين اجتنبوا الكفر والمعاصي، وأقبلوا على الله بالطاعة."));
        alshoaraaExes.add(new AlshoaraaEx("وَبُرِّزَتِ الْجَحِيمُ لِلْغَاوِينَ (91)"));
        alshoaraaExes.add(new AlshoaraaEx("وأُظهرت النار للكافرين الذين ضَلُّوا عن الهدى، وتجرَّؤوا على محارم الله وكذَّبوا رسله."));
        alshoaraaExes.add(new AlshoaraaEx("وَقِيلَ لَهُمْ أَيْنَ مَا كُنْتُمْ تَعْبُدُونَ (92)"));
        alshoaraaExes.add(new AlshoaraaEx("وقيل لهم توبيخًا: أين آلهتكم التي كنتم تعبدونها مِن دون الله، وتزعمون أنها تشفع لكم اليوم؟"));
        alshoaraaExes.add(new AlshoaraaEx("مِنْ دُونِ اللَّهِ هَلْ يَنْصُرُونَكُمْ أَوْ يَنْتَصِرُونَ (93)"));
        alshoaraaExes.add(new AlshoaraaEx("هل ينصرونكم، فيدفعون العذاب عنكم، أو ينتصرون بدفع العذاب عن أنفسهم؟ لا شيء من ذلك."));
        alshoaraaExes.add(new AlshoaraaEx("فَكُبْكِبُوا فِيهَا هُمْ وَالْغَاوُونَ (94)"));
        alshoaraaExes.add(new AlshoaraaEx("فجُمِعوا وألقُوا في جهنم، هم والذين أضلوهم."));
        alshoaraaExes.add(new AlshoaraaEx("وَجُنُودُ إِبْلِيسَ أَجْمَعُونَ (95)"));
        alshoaraaExes.add(new AlshoaraaEx("وأعوان إبليس الذين زيَّنوا لهم الشر، لم يُفْلِت منهم أحد."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا وَهُمْ فِيهَا يَخْتَصِمُونَ (96)"));
        alshoaraaExes.add(new AlshoaraaEx("قالوا معترفين بخطئهم، وهم يتنازعون في جهنم مع مَن أضلوهم."));
        alshoaraaExes.add(new AlshoaraaEx("تَاللَّهِ إِنْ كُنَّا لَفِي ضَلَالٍ مُبِينٍ (97)"));
        alshoaraaExes.add(new AlshoaraaEx("تالله إننا كنا في الدنيا في ضلال واضح لا خفاء فيه."));
        alshoaraaExes.add(new AlshoaraaEx("إِذْ نُسَوِّيكُمْ بِرَبِّ الْعَالَمِينَ (98)"));
        alshoaraaExes.add(new AlshoaraaEx("إذ نسويكم برب العالمين المستحق للعبادة وحده."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَضَلَّنَا إِلَّا الْمُجْرِمُونَ (99)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أوقعنا في هذا المصير السيِّئ إلا المجرمون الذين دعونا إلى عبادة غير الله فاتبعناهم."));
        alshoaraaExes.add(new AlshoaraaEx("فَمَا لَنَا مِنْ شَافِعِينَ (100)"));
        alshoaraaExes.add(new AlshoaraaEx("فلا أحدَ يشفع لنا، ويخلِّصنا من العذاب."));
        alshoaraaExes.add(new AlshoaraaEx("وَلَا صَدِيقٍ حَمِيمٍ (101)"));
        alshoaraaExes.add(new AlshoaraaEx("ولا مَن يَصْدُق في مودتنا ويشفق علينا."));
        alshoaraaExes.add(new AlshoaraaEx("فَلَوْ أَنَّ لَنَا كَرَّةً فَنَكُونَ مِنَ الْمُؤْمِنِينَ (102)"));
        alshoaraaExes.add(new AlshoaraaEx("فليت لنا رجعة إلى الدنيا، فنصير من جملة المؤمنين الناجين."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّ فِي ذَلِكَ لَآيَةً وَمَا كَانَ أَكْثَرُهُمْ مُؤْمِنِينَ (103)"));
        alshoaraaExes.add(new AlshoaraaEx("إن في نبأ إبراهيم السابق لَعبرة لِمن يعتبر، وما صار أكثر الذين سمعوا هذا النبأ مؤمنين."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ (104)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن ربك لهو العزيز القادر على الانتقام من المكذبين، الرحيم بعباده المؤمنين."));
        alshoaraaExes.add(new AlshoaraaEx("كَذَّبَتْ قَوْمُ نُوحٍ الْمُرْسَلِينَ (105)"));
        alshoaraaExes.add(new AlshoaraaEx("كَذَّبت قوم نوح رسالة نبيهم، فكانوا بهذا مكذبين لجميع الرسل; لأن كل رسول يأمر بتصديق جميع الرسل."));
        alshoaraaExes.add(new AlshoaraaEx("إِذْ قَالَ لَهُمْ أَخُوهُمْ نُوحٌ أَلَا تَتَّقُونَ (106)"));
        alshoaraaExes.add(new AlshoaraaEx("إذ قال لهم أخوهم نوح: ألا تخشون الله بترك عبادة غيره؟"));
        alshoaraaExes.add(new AlshoaraaEx("إِنِّي لَكُمْ رَسُولٌ أَمِينٌ (107)"));
        alshoaraaExes.add(new AlshoaraaEx("إني لكم رسول أمين فيما أبلغكم."));
        alshoaraaExes.add(new AlshoaraaEx("فَاتَّقُوا اللَّهَ وَأَطِيعُونِ (108)"));
        alshoaraaExes.add(new AlshoaraaEx("فاجعلوا الإيمان وقاية لكم من عذاب الله وأطيعوني فيما آمركم به من عبادته وحده."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ إِنْ أَجْرِيَ إِلَّا عَلَى رَبِّ الْعَالَمِينَ (109)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أطلب منكم أجرًا على تبليغ الرسالة، ما أجري إلا على رب العالمين، المتصرف في خلقه."));
        alshoaraaExes.add(new AlshoaraaEx("فَاتَّقُوا اللَّهَ وَأَطِيعُونِ (110)"));
        alshoaraaExes.add(new AlshoaraaEx("فاحذروا عقابه، وأطيعوني بامتثال أوامره، واجتناب نواهيه."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا أَنُؤْمِنُ لَكَ وَاتَّبَعَكَ الْأَرْذَلُونَ (111)"));
        alshoaraaExes.add(new AlshoaraaEx("قال له قومه: كيف نصدِّقك ونتبعك، والذين اتبعوك أراذل الناس وأسافلهم؟"));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ وَمَا عِلْمِي بِمَا كَانُوا يَعْمَلُونَ (112)"));
        alshoaraaExes.add(new AlshoaraaEx("فأجابهم نوح عليه السلام بقوله: لست مكلفًا بمعرفة أعمالهم، إنما كُلفت أن أدعوهم إلى الإيمان. والاعتبار بالإيمان لا بالحسب والنسب والحِرف والصنائع."));
        alshoaraaExes.add(new AlshoaraaEx("إِنْ حِسَابُهُمْ إِلَّا عَلَى رَبِّي لَوْ تَشْعُرُونَ (113)"));
        alshoaraaExes.add(new AlshoaraaEx("ما حسابهم للجزاء على أعمالهم وبواطنهم إلا على ربي المطَّلِع على السرائر. لو كنتم تشعرون بذلك لما قلتم هذا الكلام."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَنَا بِطَارِدِ الْمُؤْمِنِينَ (114)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أنا بطارد الذين يؤمنون بدعوتي، مهما تكن حالهم؛ تلبية لرغبتكم كي تؤمنوا بي."));
        alshoaraaExes.add(new AlshoaraaEx("إِنْ أَنَا إِلَّا نَذِيرٌ مُبِينٌ (115)"));
        alshoaraaExes.add(new AlshoaraaEx("ما أنا إلا نذير بيِّن الإنذار."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا لَئِنْ لَمْ تَنْتَهِ يَانُوحُ لَتَكُونَنَّ مِنَ الْمَرْجُومِينَ (116)"));
        alshoaraaExes.add(new AlshoaraaEx("عدل قوم نوح عن المحاورة إلى التهديد، فقالوا له: لئن لم ترجع -يا نوح- عن دعوتك لتكوننَّ مِنَ المقتولين رميًا بالحجارة."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ رَبِّ إِنَّ قَوْمِي كَذَّبُونِ (117)"));
        alshoaraaExes.add(new AlshoaraaEx("فلما سمع نوح قولهم هذا دعا ربه بقوله: رب إن قومي أصروا على تكذيبي."));
        alshoaraaExes.add(new AlshoaraaEx("فَافْتَحْ بَيْنِي وَبَيْنَهُمْ فَتْحًا وَنَجِّنِي وَمَنْ مَعِيَ مِنَ الْمُؤْمِنِينَ (118)"));
        alshoaraaExes.add(new AlshoaraaEx("فاحكم بيني وبينهم حكمًا تُهلك به مَن جحد توحيدك وكذَّب رسولك، ونجني ومَن معي من المؤمنين مما تعذب به الكافرين."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَنْجَيْنَاهُ وَمَنْ مَعَهُ فِي الْفُلْكِ الْمَشْحُونِ (119)"));
        alshoaraaExes.add(new AlshoaraaEx("فأنجيناه ومَن معه في السفينة المملوءة بصنوف المخلوقات التي حملها معه."));
        alshoaraaExes.add(new AlshoaraaEx("ثُمَّ أَغْرَقْنَا بَعْدُ الْبَاقِينَ (120)"));
        alshoaraaExes.add(new AlshoaraaEx("ثم أغرقنا بعد إنجاء نوح ومن معه الباقين، الذين لم يؤمنوا مِن قومه وردُّوا عليه النصيحة."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّ فِي ذَلِكَ لَآيَةً وَمَا كَانَ أَكْثَرُهُمْ مُؤْمِنِينَ (121)"));
        alshoaraaExes.add(new AlshoaraaEx("إن في نبأ نوح وما كان من إنجاء المؤمنين وإهلاك المكذبين لَعلامة وعبرةً عظيمة لمن بعدهم، وما كان أكثر الذين سمعوا هذه القصة مؤمنين بالله وبرسوله وشرعه."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ (122)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن ربك لهو العزيز في انتقامه ممن كفر به وخالف أمره، الرحيم بعباده المؤمنين."));
        alshoaraaExes.add(new AlshoaraaEx("كَذَّبَتْ عَادٌ الْمُرْسَلِينَ (123)"));
        alshoaraaExes.add(new AlshoaraaEx("كذَّبت قبيلة عاد رسولهم هودًا -عليه السلام- فكانوا بهذا مكذِّبين لجميع الرسل؛ لاتحاد دعوتهم في أصولها وغايتها."));
        alshoaraaExes.add(new AlshoaraaEx("إِذْ قَالَ لَهُمْ أَخُوهُمْ هُودٌ أَلَا تَتَّقُونَ (124)"));
        alshoaraaExes.add(new AlshoaraaEx("إذ قال لهم أخوهم هود: ألا تخشون الله فتخلصوا له العبادة؟"));
        alshoaraaExes.add(new AlshoaraaEx("إِنِّي لَكُمْ رَسُولٌ أَمِينٌ (125)"));
        alshoaraaExes.add(new AlshoaraaEx("إني مرسَل إليكم لهدايتكم وإرشادكم، حفيظ على رسالة الله، أبلِّغها لكم كما أمرني ربي."));
        alshoaraaExes.add(new AlshoaraaEx("فَاتَّقُوا اللَّهَ وَأَطِيعُونِ (126)"));
        alshoaraaExes.add(new AlshoaraaEx("افوا عقاب الله وأطيعوني فيما جئتكم به من عند الله."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ إِنْ أَجْرِيَ إِلَّا عَلَى رَبِّ الْعَالَمِينَ (127)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أطلب منكم على إرشادكم إلى التوحيد أيَّ نوع من أنواع الأجر، ما أجري إلا على رب العالمين."));
        alshoaraaExes.add(new AlshoaraaEx("أَتَبْنُونَ بِكُلِّ رِيعٍ آيَةً تَعْبَثُونَ (128)"));
        alshoaraaExes.add(new AlshoaraaEx("أتبنون بكل مكان مرتفع بناء عاليًا تشرفون منه فتسخرون مِنَ المارة؟ وذلك عبث وإسراف لا يعود عليكم بفائدة في الدين أو الدنيا."));
        alshoaraaExes.add(new AlshoaraaEx("وَتَتَّخِذُونَ مَصَانِعَ لَعَلَّكُمْ تَخْلُدُونَ (129)"));
        alshoaraaExes.add(new AlshoaraaEx("وتتخذون قصورًا منيعة وحصونًا مشيَّدة، كأنكم تخلدون في الدنيا ولا تموتون."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِذَا بَطَشْتُمْ بَطَشْتُمْ جَبَّارِينَ (130)"));
        alshoaraaExes.add(new AlshoaraaEx("وإذا بطشتم بأحد من الخلق قتلا أو ضربًا، فعلتم ذلك قاهرين ظالمين."));
        alshoaraaExes.add(new AlshoaraaEx("فَاتَّقُوا اللَّهَ وَأَطِيعُونِ (131)"));
        alshoaraaExes.add(new AlshoaraaEx("فخافوا الله، وامتثلوا ما أدعوكم إليه فإنه أنفع لكم."));
        alshoaraaExes.add(new AlshoaraaEx("وَاتَّقُوا الَّذِي أَمَدَّكُمْ بِمَا تَعْلَمُونَ (132)"));
        alshoaraaExes.add(new AlshoaraaEx("واخشوا الله الذي أعطاكم من أنواع النعم ما لا خفاء فيه عليكم."));
        alshoaraaExes.add(new AlshoaraaEx("أَمَدَّكُمْ بِأَنْعَامٍ وَبَنِينَ (133)"));
        alshoaraaExes.add(new AlshoaraaEx("أعطاكم الأنعام: من الإبل والبقر والغنم، وأعطاكم الأولاد."));
        alshoaraaExes.add(new AlshoaraaEx("وَجَنَّاتٍ وَعُيُونٍ (134)"));
        alshoaraaExes.add(new AlshoaraaEx("وأعطاكم البساتين المثمرة، وفجَّر لكم الماء من العيون الجارية."));
        alshoaraaExes.add(new AlshoaraaEx("إِنِّي أَخَافُ عَلَيْكُمْ عَذَابَ يَوْمٍ عَظِيمٍ (135) "));
        alshoaraaExes.add(new AlshoaraaEx("قال هود -عليه السَّلام- محذرًا لهم: إني أخاف إن أصررتم على ما أنتم عليه من التكذيب والظلم وكُفْر النِّعم، أن ينزل الله بكم عذابًا في يوم تعظم شدته من هول عذابه."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا سَوَاءٌ عَلَيْنَا أَوَعَظْتَ أَمْ لَمْ تَكُنْ مِنَ الْوَاعِظِينَ (136)"));
        alshoaraaExes.add(new AlshoaraaEx("قالوا له: يستوي عندنا تذكيرك وتخويفك لنا وتركه، فلن نؤمن لك."));
        alshoaraaExes.add(new AlshoaraaEx("إِنْ هَذَا إِلَّا خُلُقُ الْأَوَّلِينَ (137)"));
        alshoaraaExes.add(new AlshoaraaEx("وقالوا: ما هذا الذي نحن عليه إلا دين الأولين وعاداتهم."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا نَحْنُ بِمُعَذَّبِينَ (138)"));
        alshoaraaExes.add(new AlshoaraaEx("وما نحن بمعذبين على ما نفعل مما حَذَّرْتنا منه من العذاب."));
        alshoaraaExes.add(new AlshoaraaEx("فَكَذَّبُوهُ فَأَهْلَكْنَاهُمْ إِنَّ فِي ذَلِكَ لَآيَةً وَمَا كَانَ أَكْثَرُهُمْ مُؤْمِنِينَ (139)"));
        alshoaraaExes.add(new AlshoaraaEx("فاستمَرُّوا على تكذيبه، فأهلكهم الله بريح باردة شديدة. إن في ذلك الإهلاك لَعبرة لمن بعدهم، وما كان أكثر الذين سمعوا قصتهم مؤمنين بك."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ (140)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن ربك لهو العزيز الغالب على ما يريده من إهلاك المكذبين، الرحيم بالمؤمنين."));
        alshoaraaExes.add(new AlshoaraaEx("كَذَّبَتْ ثَمُودُ الْمُرْسَلِينَ (141)"));
        alshoaraaExes.add(new AlshoaraaEx("كذَّبت قبيلة ثمود أخاهم صالحًا في رسالته ودعوته إلى توحيد الله، فكانوا بهذا مكذِّبين لجميع الرسل; لأنهم جميعًا يدعون إلى توحيد الله."));
        alshoaraaExes.add(new AlshoaraaEx("إِذْ قَالَ لَهُمْ أَخُوهُمْ صَالِحٌ أَلَا تَتَّقُونَ (142)"));
        alshoaraaExes.add(new AlshoaraaEx("إذ قال لهم أخوهم صالح: ألا تخشون عقاب الله، فتُفرِدونه بالعبادة؟"));
        alshoaraaExes.add(new AlshoaraaEx("إِنِّي لَكُمْ رَسُولٌ أَمِينٌ (143)"));
        alshoaraaExes.add(new AlshoaraaEx("إني مرسَل من الله إليكم، حفيظ على هذه الرسالة كما تلقيتها عن الله."));
        alshoaraaExes.add(new AlshoaraaEx("فَاتَّقُوا اللَّهَ وَأَطِيعُونِ (144)"));
        alshoaraaExes.add(new AlshoaraaEx("فاحذروا عقابه تعالى، وامتثلوا ما دعوتكم إليه."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ إِنْ أَجْرِيَ إِلَّا عَلَى رَبِّ الْعَالَمِينَ (145)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أطلب منكم على نصحي وإرشادي لكم أي جزاء، ما جزائي إلا على رب العالمين."));
        alshoaraaExes.add(new AlshoaraaEx("أَتُتْرَكُونَ فِي مَا هَاهُنَا آمِنِينَ (146)"));
        alshoaraaExes.add(new AlshoaraaEx("أيترككم ربكم فيما أنتم فيه من النعيم مستقرين في هذه الدنيا آمنين من العذاب والزوال والموت؟"));
        alshoaraaExes.add(new AlshoaraaEx("فِي جَنَّاتٍ وَعُيُونٍ (147)"));
        alshoaraaExes.add(new AlshoaraaEx("في حدائق مثمرة وعيون جارية."));
        alshoaraaExes.add(new AlshoaraaEx("وَزُرُوعٍ وَنَخْلٍ طَلْعُهَا هَضِيمٌ (148)"));
        alshoaraaExes.add(new AlshoaraaEx("وزروع كثيرة ونخل ثمرها يانع لين نضيج."));
        alshoaraaExes.add(new AlshoaraaEx("وَتَنْحِتُونَ مِنَ الْجِبَالِ بُيُوتًا فَارِهِينَ (149)"));
        alshoaraaExes.add(new AlshoaraaEx("وتنحتون من الجبال بيوتًا ماهرين بنحتها، أَشِرين بَطِرين."));
        alshoaraaExes.add(new AlshoaraaEx("فَاتَّقُوا اللَّهَ وَأَطِيعُونِ (150)"));
        alshoaraaExes.add(new AlshoaraaEx("فخافوا عقوبة الله، واقبلوا نصحي."));
        alshoaraaExes.add(new AlshoaraaEx("وَلَا تُطِيعُوا أَمْرَ الْمُسْرِفِينَ (151)"));
        alshoaraaExes.add(new AlshoaraaEx("ولا تنقادوا لأمر المسرفين على أنفسهم المتمادين في معصية الله."));
        alshoaraaExes.add(new AlshoaraaEx("الَّذِينَ يُفْسِدُونَ فِي الْأَرْضِ وَلَا يُصْلِحُونَ (152)"));
        alshoaraaExes.add(new AlshoaraaEx("الذين دأبوا على الإفساد في الأرض إفسادًا لا إصلاح فيه."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا إِنَّمَا أَنْتَ مِنَ الْمُسَحَّرِينَ (153)"));
        alshoaraaExes.add(new AlshoaraaEx("قالت ثمود لنبيها صالح: ما أنت إلا من الذين سُحروا سِحْرًا كثيرًا، حتى غلب السحر على عقلك."));
        alshoaraaExes.add(new AlshoaraaEx("مَا أَنْتَ إِلَّا بَشَرٌ مِثْلُنَا فَأْتِ بِآيَةٍ إِنْ كُنْتَ مِنَ الصَّادِقِينَ (154)"));
        alshoaraaExes.add(new AlshoaraaEx("ما أنت إلا فرد مماثل لنا في البشرية من بني آدم، فكيف تتميز علينا بالرسالة؟ فأت بحجة واضحة تدل على ثبوت رسالتك، إن كنت صادقًا في دعواك أن الله أرسلك إلينا."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ هَذِهِ نَاقَةٌ لَهَا شِرْبٌ وَلَكُمْ شِرْبُ يَوْمٍ مَعْلُومٍ (155)"));
        alshoaraaExes.add(new AlshoaraaEx("قال لهم صالح -وقد أتاهم بناقة أخرجها الله له من الصخرة-: هذه ناقة الله لها نصيب من الماء في يوم معلوم، ولكم نصيب منه في يوم آخر. ليس لكم أن تشربوا في اليوم الذي هو نصيبها، ولا هي تشرب في اليوم الذي هو نصيبكم"));
        alshoaraaExes.add(new AlshoaraaEx("وَلَا تَمَسُّوهَا بِسُوءٍ فَيَأْخُذَكُمْ عَذَابُ يَوْمٍ عَظِيمٍ (156)"));
        alshoaraaExes.add(new AlshoaraaEx("ولا تنالوها بشيء مما يسوءها كضَرْبٍ أو قتل أو نحو ذلك، فيهلككم الله بعذابِ يومٍ تعظم شدته؛ بسبب ما يقع فيه من الهول والشدة."));
        alshoaraaExes.add(new AlshoaraaEx("فَعَقَرُوهَا فَأَصْبَحُوا نَادِمِينَ (157)"));
        alshoaraaExes.add(new AlshoaraaEx("فنحروا الناقة، فأصبحوا متحسرين على ما فعلوا لَمَّا أيقنوا بالعذاب، فلم ينفعهم ندمهم."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَخَذَهُمُ الْعَذَابُ إِنَّ فِي ذَلِكَ لَآيَةً وَمَا كَانَ أَكْثَرُهُمْ مُؤْمِنِينَ (158)"));
        alshoaraaExes.add(new AlshoaraaEx("فنزل بهم عذاب الله الذي توعدهم به صالح عليه السلام، فأهلكهم. إن في إهلاك ثمود لَعبرة لمن اعتبر بهذا المصير، وما كان أكثرهم مؤمنين."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ (159)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن ربك لهو العزيز القاهر المنتقم من أعدائه المكذبين، الرحيم بمن آمن من خلقه."));
        alshoaraaExes.add(new AlshoaraaEx("كَذَّبَتْ قَوْمُ لُوطٍ الْمُرْسَلِينَ (160)"));
        alshoaraaExes.add(new AlshoaraaEx("كَذَّبت قوم لوط برسالته، فكانوا بهذا مكذبين لسائر رسل الله؛ لأن ما جاؤوا به من التوحيد وأصول الشرائع واحد."));
        alshoaraaExes.add(new AlshoaraaEx("إِذْ قَالَ لَهُمْ أَخُوهُمْ لُوطٌ أَلَا تَتَّقُونَ (161)"));
        alshoaraaExes.add(new AlshoaraaEx("إذ قال لهم أخوهم لوط: ألا تخشون عذاب الله؟"));
        alshoaraaExes.add(new AlshoaraaEx("إِنِّي لَكُمْ رَسُولٌ أَمِينٌ (162)"));
        alshoaraaExes.add(new AlshoaraaEx("إني رسول من ربكم، أمين على تبليغ رسالته إليكم."));
        alshoaraaExes.add(new AlshoaraaEx("فَاتَّقُوا اللَّهَ وَأَطِيعُونِ (163)"));
        alshoaraaExes.add(new AlshoaraaEx("فاحذروا عقاب الله على تكذيبكم رسوله، واتبعوني فيما دعوتكم إليه."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ إِنْ أَجْرِيَ إِلَّا عَلَى رَبِّ الْعَالَمِينَ (164)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أسألكم على دعوتي لهدايتكم أيَّ أجر، ما أجري إلا على رب العالمين."));
        alshoaraaExes.add(new AlshoaraaEx("أَتَأْتُونَ الذُّكْرَانَ مِنَ الْعَالَمِينَ (165)"));
        alshoaraaExes.add(new AlshoaraaEx("أتنكحون الذكور مِن بني آدم."));
        alshoaraaExes.add(new AlshoaraaEx("وَتَذَرُونَ مَا خَلَقَ لَكُمْ رَبُّكُمْ مِنْ أَزْوَاجِكُمْ بَلْ أَنْتُمْ قَوْمٌ عَادُونَ (166)"));
        alshoaraaExes.add(new AlshoaraaEx("وتتركون ما خلق الله لاستمتاعكم وتناسلكم مِن أزواجكم؟ بل أنتم قوم -بهذه المعصية- متجاوزون ما أباحه الله لكم من الحلال إلى الحرام."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا لَئِنْ لَمْ تَنْتَهِ يَالُوطُ لَتَكُونَنَّ مِنَ الْمُخْرَجِينَ (167)"));
        alshoaraaExes.add(new AlshoaraaEx("قال قوم لوط: لئن لم تترك يا لوط نَهْيَنا عن إتيان الذكور وتقبيح فعله، لتكونن من المطرودين من بلادنا."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ إِنِّي لِعَمَلِكُمْ مِنَ الْقَالِينَ (168)"));
        alshoaraaExes.add(new AlshoaraaEx("قال لوط لهم: إني لِعملكم الذي تعملونه من إتيان الذكور، لَمن المبغضين له بغضًا شديدًا."));
        alshoaraaExes.add(new AlshoaraaEx("رَبِّ نَجِّنِي وَأَهْلِي مِمَّا يَعْمَلُونَ (169)"));
        alshoaraaExes.add(new AlshoaraaEx("ثم دعا لوط ربه حينما يئس من استجابتهم له قائلا ربِّ أنقذني وأنقذ أهلي مما يعمله قومي مِن هذه المعصية القبيحة، ومِن عقوبتك التي ستصيبهم."));
        alshoaraaExes.add(new AlshoaraaEx("فَنَجَّيْنَاهُ وَأَهْلَهُ أَجْمَعِينَ (170)"));
        alshoaraaExes.add(new AlshoaraaEx("فنجيناه وأهل بيته والمستجيبين لدعوته أجمعين."));
        alshoaraaExes.add(new AlshoaraaEx("إِلَّا عَجُوزًا فِي الْغَابِرِينَ (171)"));
        alshoaraaExes.add(new AlshoaraaEx("إلا عجوزًا من أهله، وهي امرأته، لم تشاركهم في الإيمان، فكانت من الباقين في العذاب والهلاك."));
        alshoaraaExes.add(new AlshoaraaEx("ثُمَّ دَمَّرْنَا الْآخَرِينَ (172)"));
        alshoaraaExes.add(new AlshoaraaEx("ثم أهلكنا مَن عداهم من الكفرة أشدَّ إهلاك."));
        alshoaraaExes.add(new AlshoaraaEx("وَأَمْطَرْنَا عَلَيْهِمْ مَطَرًا فَسَاءَ مَطَرُ الْمُنْذَرِينَ (173)"));
        alshoaraaExes.add(new AlshoaraaEx("وأنزلنا عليهم حجارة من السماء كالمطر أهلكتهم، فقَبُحَ مطرُ من أنذرهم رسلهم ولم يستجيبوا لهم؛ فقد أُنزل بهم أشدُّ أنواع الهلاك والتدمير."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّ فِي ذَلِكَ لَآيَةً وَمَا كَانَ أَكْثَرُهُمْ مُؤْمِنِينَ (174)"));
        alshoaraaExes.add(new AlshoaraaEx("إن في ذلك العقاب الذي نزل بقوم لوط لَعبرة وموعظة، يتعظ بها المكذبون. وما كان أكثرهم مؤمنين."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ (175)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن ربك لهو العزيز الغالب الذي يقهر المكذبين، الرحيم بعباده المؤمنين."));
        alshoaraaExes.add(new AlshoaraaEx("كَذَّبَ أَصْحَابُ الْأَيْكَةِ الْمُرْسَلِينَ (176)"));
        alshoaraaExes.add(new AlshoaraaEx("كذَّب أصحاب الأرض ذات الشجر الملتف رسولهم شعيبًا في رسالته، فكانوا بهذا مكذِّبين لجميع الرسالات."));
        alshoaraaExes.add(new AlshoaraaEx("إِذْ قَالَ لَهُمْ شُعَيْبٌ أَلَا تَتَّقُونَ (177)"));
        alshoaraaExes.add(new AlshoaraaEx("إذ قال لهم شعيب: ألا تخشون عقاب الله على شرككم ومعاصيكم؟"));
        alshoaraaExes.add(new AlshoaraaEx("إِنِّي لَكُمْ رَسُولٌ أَمِينٌ (178)"));
        alshoaraaExes.add(new AlshoaraaEx("إني مرسَل إليكم مِنَ الله لهدايتكم، حفيظ على ما أوحى الله به إليَّ من الرسالة."));
        alshoaraaExes.add(new AlshoaraaEx("فَاتَّقُوا اللَّهَ وَأَطِيعُونِ (179)"));
        alshoaraaExes.add(new AlshoaraaEx("فخافوا عقاب الله، واتبعوا ما دعوتكم إليه مِن هداية الله؛ لترشدوا."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَسْأَلُكُمْ عَلَيْهِ مِنْ أَجْرٍ إِنْ أَجْرِيَ إِلَّا عَلَى رَبِّ الْعَالَمِينَ (180)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أطلب منكم على دعائي لكم إلى الإيمان بالله أيَّ جزاء، ما جزائي إلا على رب العالمين."));
        alshoaraaExes.add(new AlshoaraaEx("أَوْفُوا الْكَيْلَ وَلَا تَكُونُوا مِنَ الْمُخْسِرِينَ (181)"));
        alshoaraaExes.add(new AlshoaraaEx("قال لهم شعيب -وقد كانوا يُنْقِصون الكيل والميزان-: أتمُّوا الكيل للناس وافيًا لهم، ولا تكونوا ممن يُنْقِصون الناس حقوقهم."));
        alshoaraaExes.add(new AlshoaraaEx("وَزِنُوا بِالْقِسْطَاسِ الْمُسْتَقِيمِ (182)"));
        alshoaraaExes.add(new AlshoaraaEx("وَزِنوا بالميزان العدل المستقيم."));
        alshoaraaExes.add(new AlshoaraaEx("وَلَا تَبْخَسُوا النَّاسَ أَشْيَاءَهُمْ وَلَا تَعْثَوْا فِي الْأَرْضِ مُفْسِدِينَ (183)"));
        alshoaraaExes.add(new AlshoaraaEx("ولا تنقصوا الناس شيئًا مِن حقوقهم في كيل أو وزن أو غير ذلك، ولا تكثروا في الأرض الفساد، بالشرك والقتل والنهب وتخويف الناس وارتكاب المعاصي."));
        alshoaraaExes.add(new AlshoaraaEx("وَاتَّقُوا الَّذِي خَلَقَكُمْ وَالْجِبِلَّةَ الْأَوَّلِينَ (184)"));
        alshoaraaExes.add(new AlshoaraaEx("واحذروا عقوبة الله الذي خلقكم وخلق الأمم المتقدمة عليكم."));
        alshoaraaExes.add(new AlshoaraaEx("قَالُوا إِنَّمَا أَنْتَ مِنَ الْمُسَحَّرِينَ (185)"));
        alshoaraaExes.add(new AlshoaraaEx("قالوا: إنما أنت -يا شعيب- مِنَ الذين أصابهم السحر إصابة شديدة، فذهب بعقولهم."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَنْتَ إِلَّا بَشَرٌ مِثْلُنَا وَإِنْ نَظُنُّكَ لَمِنَ الْكَاذِبِينَ (186)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أنت إلا واحد مثلنا في البشرية، فكيف تختص دوننا بالرسالة؟ وإن أكبر ظننا أنك من الكاذبين فيما تدَّعيه من الرسالة."));
        alshoaraaExes.add(new AlshoaraaEx("فَأَسْقِطْ عَلَيْنَا كِسَفًا مِنَ السَّمَاءِ إِنْ كُنْتَ مِنَ الصَّادِقِينَ (187)"));
        alshoaraaExes.add(new AlshoaraaEx("فإن كنت صادقًا في دعوى النبوة، فادع الله أن يسقط علينا قطع عذاب من السماء تستأصلنا."));
        alshoaraaExes.add(new AlshoaraaEx("قَالَ رَبِّي أَعْلَمُ بِمَا تَعْمَلُونَ (188)"));
        alshoaraaExes.add(new AlshoaraaEx("قال لهم شعيب: ربي أعلم بما تعملونه مِنَ الشرك والمعاصي، وبما تستوجبونه من العقاب."));
        alshoaraaExes.add(new AlshoaraaEx("فَكَذَّبُوهُ فَأَخَذَهُمْ عَذَابُ يَوْمِ الظُّلَّةِ إِنَّهُ كَانَ عَذَابَ يَوْمٍ عَظِيمٍ (189)"));
        alshoaraaExes.add(new AlshoaraaEx("فاستمَرُّوا على تكذيبه، فأصابهم الحر الشديد، وصاروا يبحثون عن ملاذ يستظلون به، فأظلتهم سحابة، وجدوا لها بردًا ونسيمًا، فلما اجتمعوا تحتها، التهبت عليهم نارًا فأحرقتهم، فكان هلاكهم جميعًا في يوم شديد الهول."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّ فِي ذَلِكَ لَآيَةً وَمَا كَانَ أَكْثَرُهُمْ مُؤْمِنِينَ (190)"));
        alshoaraaExes.add(new AlshoaraaEx("إن في ذلك العقاب الذي نزل بهم، لَدلالة واضحة على قدرة الله في مؤاخذة المكذبين، وعبرة لمن يعتبر، وما كان أكثرهم مؤمنين متعظين بذلك."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّ رَبَّكَ لَهُوَ الْعَزِيزُ الرَّحِيمُ (191)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن ربك - أيها الرسول - لهو العزيز في نقمته ممن انتقم منه من أعدائه، الرحيم بعباده الموحدين."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّهُ لَتَنْزِيلُ رَبِّ الْعَالَمِينَ (192)"));
        alshoaraaExes.add(new AlshoaraaEx("وإن هذا القرآن الذي ذُكِرَتْ فيه هذه القصص الصادقة، لَمنزَّل مِن خالق الخلق، ومالك الأمر كله."));
        alshoaraaExes.add(new AlshoaraaEx("نَزَلَ بِهِ الرُّوحُ الْأَمِينُ (193)"));
        alshoaraaExes.add(new AlshoaraaEx("نزل به جبريل الأمين، فتلاه عليك - أيها الرسول -."));
        alshoaraaExes.add(new AlshoaraaEx("عَلَى قَلْبِكَ لِتَكُونَ مِنَ الْمُنْذِرِينَ (194)"));
        alshoaraaExes.add(new AlshoaraaEx("حتى وعيته بقلبك حفظًا وفهمًا؛ لتكون مِن رسل الله الذين يخوِّفون قومهم عقاب الله، فتنذر بهذا التنزيل الإنس والجن أجمعين."));
        alshoaraaExes.add(new AlshoaraaEx("بِلِسَانٍ عَرَبِيٍّ مُبِينٍ (195)"));
        alshoaraaExes.add(new AlshoaraaEx("نزل به جبريل عليك بلغة عربية واضحة المعنى، ظاهرة الدلالة، فيما يحتاجون إليه في إصلاح شؤون دينهم ودنياهم."));
        alshoaraaExes.add(new AlshoaraaEx("وَإِنَّهُ لَفِي زُبُرِ الْأَوَّلِينَ (196)"));
        alshoaraaExes.add(new AlshoaraaEx("وإنَّ ذِكْرَ هذا القرآن لَمثبتٌ في كتب الأنبياء السابقين، قد بَشَّرَتْ به وصَدَّقَتْه."));
        alshoaraaExes.add(new AlshoaraaEx("أَوَلَمْ يَكُنْ لَهُمْ آيَةً أَنْ يَعْلَمَهُ عُلَمَاءُ بَنِي إِسْرَائِيلَ (197)"));
        alshoaraaExes.add(new AlshoaraaEx("أو لم يَكْفِ هؤلاء -في الدلالة على أنك رسول الله، وأن القرآن حق- عِلْمُ علماء بني إسرائيل صحة ذلك، ومَن آمن منهم كعبد الله بن سلام؟"));
        alshoaraaExes.add(new AlshoaraaEx("وَلَوْ نَزَّلْنَاهُ عَلَى بَعْضِ الْأَعْجَمِينَ (198)"));
        alshoaraaExes.add(new AlshoaraaEx("ولو نَزَّلنا القرآن على بعض الذين لا يتكلمون بالعربية."));
        alshoaraaExes.add(new AlshoaraaEx("فَقَرَأَهُ عَلَيْهِمْ مَا كَانُوا بِهِ مُؤْمِنِينَ (199)"));
        alshoaraaExes.add(new AlshoaraaEx("رأه على كفار قريش قراءة عربية صحيحة، لكفروا به أيضًا، وانتحلوا لجحودهم عذرًا."));
        alshoaraaExes.add(new AlshoaraaEx("كَذَلِكَ سَلَكْنَاهُ فِي قُلُوبِ الْمُجْرِمِينَ (200)"));
        alshoaraaExes.add(new AlshoaraaEx("كذلك أدخلنا في قلوب المجرمين جحود القرآن، وصار متمكنًا فيها؛ وذلك بسبب ظلمهم وإجرامهم."));
        alshoaraaExes.add(new AlshoaraaEx("لَا يُؤْمِنُونَ بِهِ حَتَّى يَرَوُا الْعَذَابَ الْأَلِيمَ (201)"));
        alshoaraaExes.add(new AlshoaraaEx("فلا سبيل إلى أن يتغيروا عمَّا هم عليه من إنكار القرآن، حتى يعاينوا العذاب الشديد الذي وُعِدوا به."));
        alshoaraaExes.add(new AlshoaraaEx("فَيَأْتِيَهُمْ بَغْتَةً وَهُمْ لَا يَشْعُرُونَ (202)"));
        alshoaraaExes.add(new AlshoaraaEx("فينزل بهم العذاب فجأة، وهم لا يعلمون قبل ذلك بمجيئه."));
        alshoaraaExes.add(new AlshoaraaEx("فَيَقُولُوا هَلْ نَحْنُ مُنْظَرُونَ (203)"));
        alshoaraaExes.add(new AlshoaraaEx("فيقولون عند مفاجأتهم به تحسُّرًا على ما فاتهم من الإيمان: هل نحن مُمْهَلون مُؤخَّرون؛ لنتوب إلى الله مِن شركنا، ونستدرك ما فاتنا؟"));
        alshoaraaExes.add(new AlshoaraaEx("أَفَبِعَذَابِنَا يَسْتَعْجِلُونَ (204)"));
        alshoaraaExes.add(new AlshoaraaEx("أَغَرَّ هؤلاء إمهالي، فيستعجلون نزول العذاب عليهم من السماء؟"));
        alshoaraaExes.add(new AlshoaraaEx("أَفَرَأَيْتَ إِنْ مَتَّعْنَاهُمْ سِنِينَ (205)"));
        alshoaraaExes.add(new AlshoaraaEx("أفعلمت - أيها الرسول - إن مَتَّعناهم بالحياة سنين طويلة بتأخير آجالهم."));
        alshoaraaExes.add(new AlshoaraaEx("ثُمَّ جَاءَهُمْ مَا كَانُوا يُوعَدُونَ (206)"));
        alshoaraaExes.add(new AlshoaraaEx("ثم نزل بهم العذاب الموعود؟"));
        alshoaraaExes.add(new AlshoaraaEx("مَا أَغْنَى عَنْهُمْ مَا كَانُوا يُمَتَّعُونَ (207)"));
        alshoaraaExes.add(new AlshoaraaEx("ما أغنى عنهم تمتعهم بطول العمر، وطيب العيش، إذا لم يتوبوا من شركهم؟ فعذاب الله واقع بهم عاجلا أم آجلا."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا أَهْلَكْنَا مِنْ قَرْيَةٍ إِلَّا لَهَا مُنْذِرُونَ (208)"));
        alshoaraaExes.add(new AlshoaraaEx("وما أهلكنا مِن قرية من القرى في الأمم جميعًا، إلا بعد أن نرسل إليهم رسلا ينذرونهم."));
        alshoaraaExes.add(new AlshoaraaEx("ذِكْرَى وَمَا كُنَّا ظَالِمِينَ (209)"));
        alshoaraaExes.add(new AlshoaraaEx("تذكرة لهم وتنبيهًا على ما فيه نجاتهم، وما كنا ظالمين فنعذب أمة قبل أن نرسل إليها رسولا."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا تَنَزَّلَتْ بِهِ الشَّيَاطِينُ (210)"));
        alshoaraaExes.add(new AlshoaraaEx("وما تَنَزَّلَتْ بالقرآن على محمد الشياطين -كما يزعم الكفرة-."));
        alshoaraaExes.add(new AlshoaraaEx("وَمَا يَنْبَغِي لَهُمْ وَمَا يَسْتَطِيعُونَ (211)"));
        alshoaraaExes.add(new AlshoaraaEx("ولا يصح منهم ذلك، وما يستطيعونه."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّهُمْ عَنِ السَّمْعِ لَمَعْزُولُونَ (212)"));
        alshoaraaExes.add(new AlshoaraaEx("لأنهم عن استماع القرآن من السماء محجوبون مرجومون بالشهب."));
        alshoaraaExes.add(new AlshoaraaEx("فَلَا تَدْعُ مَعَ اللَّهِ إِلَهًا آخَرَ فَتَكُونَ مِنَ الْمُعَذَّبِينَ (213)"));
        alshoaraaExes.add(new AlshoaraaEx("فلا تعبد مع الله معبودًا غيره، فينزل بك من العذاب ما نزل بهؤلاء الذين عبدوا مع الله غيره."));
        alshoaraaExes.add(new AlshoaraaEx("وَأَنْذِرْ عَشِيرَتَكَ الْأَقْرَبِينَ (214)"));
        alshoaraaExes.add(new AlshoaraaEx("وحذِّر - أيها الرسول - الأقرب فالأقرب مِن قومك، مِن عذابنا، أن ينزل بهم."));
        alshoaraaExes.add(new AlshoaraaEx("وَاخْفِضْ جَنَاحَكَ لِمَنِ اتَّبَعَكَ مِنَ الْمُؤْمِنِينَ (215)"));
        alshoaraaExes.add(new AlshoaraaEx("وأَلِنْ جانبك وكلامك تواضعًا ورحمة لمن ظهر لك منه إجابة دعوتك."));
        alshoaraaExes.add(new AlshoaraaEx("فَإِنْ عَصَوْكَ فَقُلْ إِنِّي بَرِيءٌ مِمَّا تَعْمَلُونَ (216)"));
        alshoaraaExes.add(new AlshoaraaEx("فإن خالفوا أمرك ولم يتبعوك، فتبرَّأ من أعمالهم، وما هم عليه من الشرك والضلال."));
        alshoaraaExes.add(new AlshoaraaEx("وَتَوَكَّلْ عَلَى الْعَزِيزِ الرَّحِيمِ (217)"));
        alshoaraaExes.add(new AlshoaraaEx("وفَوِّضْ أمرك إلى الله العزيز الذي لا يغالَب ولا يُقْهَر، الرحيم الذي لا يخذل أولياءه."));
        alshoaraaExes.add(new AlshoaraaEx("الَّذِي يَرَاكَ حِينَ تَقُومُ (218)"));
        alshoaraaExes.add(new AlshoaraaEx("وهو الذي يراك حين تقوم للصلاة وحدك في جوف الليل."));
        alshoaraaExes.add(new AlshoaraaEx("وَتَقَلُّبَكَ فِي السَّاجِدِينَ (219)"));
        alshoaraaExes.add(new AlshoaraaEx("ويرى تقلُّبك مع الساجدين في صلاتهم معك قائمًا وراكعًا وساجدًا وجالسًا."));
        alshoaraaExes.add(new AlshoaraaEx("إِنَّهُ هُوَ السَّمِيعُ الْعَلِيمُ (220)"));
        alshoaraaExes.add(new AlshoaraaEx("إنه -سبحانه- هو السميع لتلاوتك وذكرك، العليم بنيتك وعملك."));
        alshoaraaExes.add(new AlshoaraaEx("هَلْ أُنَبِّئُكُمْ عَلَى مَنْ تَنَزَّلُ الشَّيَاطِينُ (221)"));
        alshoaraaExes.add(new AlshoaraaEx("هل أخبركم -أيها الناس- على مَن تنزَّل الشياطين؟"));
        alshoaraaExes.add(new AlshoaraaEx("تَنَزَّلُ عَلَى كُلِّ أَفَّاكٍ أَثِيمٍ (222)"));
        alshoaraaExes.add(new AlshoaraaEx("تتنزل على كل كذَّاب كثير الآثام من الكهنة."));
        alshoaraaExes.add(new AlshoaraaEx("يُلْقُونَ السَّمْعَ وَأَكْثَرُهُمْ كَاذِبُونَ (223)"));
        alshoaraaExes.add(new AlshoaraaEx("يَسْتَرِقُ الشياطين السمع، يتخطفونه من الملأ الأعلى، فيلقونه إلى الكهان، ومَن جرى مجراهم مِنَ الفسقة، وأكثر هؤلاء كاذبون، يَصْدُق أحدهم في كلمة، فيزيد فيها أكثر مِن مائة كذبة."));
        alshoaraaExes.add(new AlshoaraaEx("وَالشُّعَرَاءُ يَتَّبِعُهُمُ الْغَاوُونَ (224)"));
        alshoaraaExes.add(new AlshoaraaEx("والشعراء يقوم شعرهم على الباطل والكذب، ويجاريهم الضالون الزائغون مِن أمثالهم."));
        alshoaraaExes.add(new AlshoaraaEx("أَلَمْ تَرَ أَنَّهُمْ فِي كُلِّ وَادٍ يَهِيمُونَ (225)"));
        alshoaraaExes.add(new AlshoaraaEx("ألم تر - أيها النبي - أنهم يذهبون كالهائم على وجهه، يخوضون في كل فن مِن فنون الكذب والزور وتمزيق الأعراض والطعن في الأنساب وتجريح النساء العفائف."));
        alshoaraaExes.add(new AlshoaraaEx("وَأَنَّهُمْ يَقُولُونَ مَا لَا يَفْعَلُونَ (226)"));
        alshoaraaExes.add(new AlshoaraaEx("وأنهم يقولون ما لا يفعلون، يبالغون في مدح أهل الباطل، وينتقصون أهل الحق؟"));
        alshoaraaExes.add(new AlshoaraaEx("إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَذَكَرُوا اللَّهَ كَثِيرًا وَانْتَصَرُوا مِنْ بَعْدِ مَا ظُلِمُوا وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ (227)"));
        alshoaraaExes.add(new AlshoaraaEx("استثنى الله من الشعراءِ الشعراءَ الذين اهتدَوْا بالإيمان وعملوا الصالحات، وأكثروا مِن ذِكْر الله فقالوا الشعر في توحيد الله -سبحانه- والثناء عليه جلَّ ذكره، والدفاع عن رسوله محمد صلى الله عليه وسلم، وتكلموا بالحكمة والموعظة والآداب الحسنة، وانتصروا للإسلام، يهجون مَن يهجوه أو يهجو رسوله، ردًّا على الشعراء الكافرين. وسيعلم الذين ظلموا أنفسهم بالشرك والمعاصي، وظلموا غيرهم بغمط حقوقهم، أو الاعتداء عليهم، أو بالتُّهم الباطلة، أي مرجع من مراجع الشر والهلاك يرجعون إليه؟ إنَّه منقلب سوء، نسأل الله السلامة والعافية."));

        quran_explanation_26_adapter = new quran_explanation_26_adapter(alshoaraaExes ,QuranExplanation_26Activity.this);

        recyclerView = findViewById(R.id.rv_explanation_26);
        recyclerView.setLayoutManager(new LinearLayoutManager(QuranExplanation_26Activity.this));
        recyclerView.setAdapter(quran_explanation_26_adapter);


    }

}