package com.example.muslim;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;

public class QuranExplanation_37Activity extends AppCompatActivity {

    ArrayList<AlsafatEx> alsafatExes = new ArrayList<>();
    RecyclerView recyclerView;
    quran_explanation_37_adapter quran_explanation_37_adapter;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_quran_explanation_37);

        alsafatExes.add(new AlsafatEx("بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ"));
        alsafatExes.add(new AlsafatEx("وَالصَّافَّاتِ صَفًّا (1)"));
        alsafatExes.add(new AlsafatEx("أقسم الله تعالى بالملائكة تصف في عبادتها صفوفًا متراصة."));
        alsafatExes.add(new AlsafatEx("فَالزَّاجِرَاتِ زَجْرًا (2)"));
        alsafatExes.add(new AlsafatEx("بالملائكة تزجر السحاب وتسوقه بأمر الله."));
        alsafatExes.add(new AlsafatEx("فَالتَّالِيَاتِ ذِكْرًا (3)"));
        alsafatExes.add(new AlsafatEx("وبالملائكة تتلو ذكر الله وكلامه تعالى."));
        alsafatExes.add(new AlsafatEx("إِنَّ إِلَهَكُمْ لَوَاحِدٌ (4)"));
        alsafatExes.add(new AlsafatEx("إن معبودكم -أيها الناس- لواحد لا شريك له، فأخلصوا له العبادة والطاعة. ويقسم الله بما شاء مِن خلقه، أما المخلوق فلا يجوز له القسم إلا بالله، فالحلف بغير الله شرك."));
        alsafatExes.add(new AlsafatEx("رَبُّ السَّمَاوَاتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا وَرَبُّ الْمَشَارِقِ (5)"));
        alsafatExes.add(new AlsafatEx("هو خالق السموات والأرض وما بينهما، ومدبِّر الشمس في مطالعها ومغاربها."));
        alsafatExes.add(new AlsafatEx("إِنَّا زَيَّنَّا السَّمَاءَ الدُّنْيَا بِزِينَةٍ الْكَوَاكِبِ (6)"));
        alsafatExes.add(new AlsafatEx("إنَّا زينَّا السماء الدنيا بزينة هي النجوم."));
        alsafatExes.add(new AlsafatEx("وَحِفْظًا مِنْ كُلِّ شَيْطَانٍ مَارِدٍ (7)"));
        alsafatExes.add(new AlsafatEx("وحفظنا السماء بالنجوم مِن كل شيطان متمرِّد عاتٍ رجيم."));
        alsafatExes.add(new AlsafatEx("لَا يَسَّمَّعُونَ إِلَى الْمَلَإِ الْأَعْلَى وَيُقْذَفُونَ مِنْ كُلِّ جَانِبٍ (8)"));
        alsafatExes.add(new AlsafatEx("لا تستطيع الشياطين أن تصل إلى الملأ الأعلى، وهي السموات ومَن فيها مِن الملائكة، فتستمع إليهم إذا تكلموا بما يوحيه الله تعالى مِن شرعه وقدره، ويُرْجَمون بالشهب من كل جهة."));
        alsafatExes.add(new AlsafatEx("دُحُورًا وَلَهُمْ عَذَابٌ وَاصِبٌ (9)"));
        alsafatExes.add(new AlsafatEx("طردًا لهم عن الاستماع، ولهم في الدار الآخرة عذاب دائم موجع."));
        alsafatExes.add(new AlsafatEx("إِلَّا مَنْ خَطِفَ الْخَطْفَةَ فَأَتْبَعَهُ شِهَابٌ ثَاقِبٌ (10)"));
        alsafatExes.add(new AlsafatEx("إلا مَنِ اختطف من الشياطين الخطفة، وهي الكلمة يسمعها من السماء بسرعة، فيلقيها إلى الذي تحته، ويلقيها الآخر إلى الذي تحته، فربما أدركه الشهاب المضيء قبل أن يلقيها، وربما ألقاها بقَدَر الله تعالى قبل أن يأتيه الشهاب، فيحرقه فيذهب بها الآخر إلى الكهنة، فيكذبون معها مائة كذبة."));
        alsafatExes.add(new AlsafatEx("فَاسْتَفْتِهِمْ أَهُمْ أَشَدُّ خَلْقًا أَمْ مَنْ خَلَقْنَا إِنَّا خَلَقْنَاهُمْ مِنْ طِينٍ لَازِبٍ (11)"));
        alsafatExes.add(new AlsafatEx("فاسأل -أيها الرسول- منكري البعث أَهُم أشد خلقًا أم من خلقنا من هذه المخلوقات؟ إنا خلقنا أباهم آدم من طين لزج، يلتصق بعضه ببعض."));
        alsafatExes.add(new AlsafatEx("بَلْ عَجِبْتَ وَيَسْخَرُونَ (12)"));
        alsafatExes.add(new AlsafatEx("بل عجبتَ -أيها الرسول- من تكذيبهم وإنكارهم البعث، وأعجب من إنكارهم وأبلغ أنهم يستهزئون بك، ويسخرون من قولك."));
        alsafatExes.add(new AlsafatEx("وَإِذَا ذُكِّرُوا لَا يَذْكُرُونَ (13)"));
        alsafatExes.add(new AlsafatEx("وإذا ذكِّروا بما نسوه أو غَفَلوا عنه لا ينتفعون بهذا الذكر ولا يتدبَّرون."));
        alsafatExes.add(new AlsafatEx("وَإِذَا رَأَوْا آيَةً يَسْتَسْخِرُونَ (14)"));
        alsafatExes.add(new AlsafatEx("وإذا رأوا معجزة دالَّة على نبوَّتك يسخرون منها ويعجبون."));
        alsafatExes.add(new AlsafatEx("وَقَالُوا إِنْ هَذَا إِلَّا سِحْرٌ مُبِينٌ (15)"));
        alsafatExes.add(new AlsafatEx("وقالوا: ما هذا الذي جئت به إلا سحر ظاهر بيِّن."));
        alsafatExes.add(new AlsafatEx("أَإِذَا مِتْنَا وَكُنَّا تُرَابًا وَعِظَامًا أَإِنَّا لَمَبْعُوثُونَ (16)"));
        alsafatExes.add(new AlsafatEx("أإذا متنا وصِرْنا ترابًا وعظامًا بالية أإنا لمبعوثون من قبورنا أحياء."));
        alsafatExes.add(new AlsafatEx("أَوَآبَاؤُنَا الْأَوَّلُونَ (17)"));
        alsafatExes.add(new AlsafatEx("أو يُبعث آباؤنا الذين مضوا من قبلنا؟"));
        alsafatExes.add(new AlsafatEx("قُلْ نَعَمْ وَأَنْتُمْ دَاخِرُونَ (18)"));
        alsafatExes.add(new AlsafatEx("قل لهم -أيها الرسول-: نعم سوف تُبعثون، وأنتم أذلاء صاغرون."));
        alsafatExes.add(new AlsafatEx("فَإِنَّمَا هِيَ زَجْرَةٌ وَاحِدَةٌ فَإِذَا هُمْ يَنْظُرُونَ (19)"));
        alsafatExes.add(new AlsafatEx("فإنما هي نفخة واحدة، فإذا هم قائمون من قبورهم ينظرون أهوال يوم القيامة."));
        alsafatExes.add(new AlsafatEx("وَقَالُوا يَاوَيْلَنَا هَذَا يَوْمُ الدِّينِ (20)"));
        alsafatExes.add(new AlsafatEx("وقالوا: يا هلاكنا هذا يوم الحساب والجزاء."));
        alsafatExes.add(new AlsafatEx("هَذَا يَوْمُ الْفَصْلِ الَّذِي كُنْتُمْ بِهِ تُكَذِّبُونَ (21)"));
        alsafatExes.add(new AlsafatEx("فيقال لهم: هذا يوم القضاء بين الخلق بالعدل الذي كنتم تكذبون به في الدنيا وتنكرونه."));
        alsafatExes.add(new AlsafatEx("احْشُرُوا الَّذِينَ ظَلَمُوا وَأَزْوَاجَهُمْ وَمَا كَانُوا يَعْبُدُونَ (22)"));
        alsafatExes.add(new AlsafatEx("ويقال للملائكة: اجمَعُوا الذين كفروا بالله ونظراءهم وآلهتهم التي كانوا يعبدونها."));
        alsafatExes.add(new AlsafatEx("مِنْ دُونِ اللَّهِ فَاهْدُوهُمْ إِلَى صِرَاطِ الْجَحِيمِ (23)"));
        alsafatExes.add(new AlsafatEx("من دون الله، فسوقوهم سوقًا عنيفًا إلى جهنم."));
        alsafatExes.add(new AlsafatEx("وَقِفُوهُمْ إِنَّهُمْ مَسْئُولُونَ (24)"));
        alsafatExes.add(new AlsafatEx("واحبسوهم قبل أن يصلوا إلى جهنم؛ إنهم مسؤولون عن أعمالهم وأقوالهم التي صدرت عنهم في الدنيا، مساءلة إنكار عليهم وتبكيت لهم."));
        alsafatExes.add(new AlsafatEx("مَا لَكُمْ لَا تَنَاصَرُونَ (25)"));
        alsafatExes.add(new AlsafatEx("ويقال لهم توبيخًا: ما لكم لا ينصر بعضكم بعضًا؟"));
        alsafatExes.add(new AlsafatEx("بَلْ هُمُ الْيَوْمَ مُسْتَسْلِمُونَ (26)"));
        alsafatExes.add(new AlsafatEx("بل هم اليوم منقادون لأمر الله، لا يخالفونه ولا يحيدون عنه، غير منتصرين لأنفسهم."));
        alsafatExes.add(new AlsafatEx("وَأَقْبَلَ بَعْضُهُمْ عَلَى بَعْضٍ يَتَسَاءَلُونَ (27)"));
        alsafatExes.add(new AlsafatEx("وأقبل بعض الكفار على بعض يتلاومون ويتخاصمون."));
        alsafatExes.add(new AlsafatEx("قَالُوا إِنَّكُمْ كُنْتُمْ تَأْتُونَنَا عَنِ الْيَمِينِ (28)"));
        alsafatExes.add(new AlsafatEx("قال الأتباع للمتبوعين: إنكم كنتم تأتوننا من قِبَل الدين والحق، فتهوِّنون علينا أمر الشريعة، وتُنَفِّروننا عنها، وتزينون لنا الضلال."));
        alsafatExes.add(new AlsafatEx("قَالُوا بَلْ لَمْ تَكُونُوا مُؤْمِنِينَ (29)"));
        alsafatExes.add(new AlsafatEx("وقال المتبوعون للتابعين: ما الأمر كما تزعمون، بل كانت قلوبكم منكرة للإيمان، قابلة للكفر والعصيان."));
        alsafatExes.add(new AlsafatEx("وَمَا كَانَ لَنَا عَلَيْكُمْ مِنْ سُلْطَانٍ بَلْ كُنْتُمْ قَوْمًا طَاغِينَ (30)"));
        alsafatExes.add(new AlsafatEx("وما كان لنا عليكم من حجة أو قوَّة، فنصدكم بها عن الإيمان، بل كنتم -أيها المشركون- قومًا طاغين متجاوزين للحق."));
        alsafatExes.add(new AlsafatEx("فَحَقَّ عَلَيْنَا قَوْلُ رَبِّنَا إِنَّا لَذَائِقُونَ (31)"));
        alsafatExes.add(new AlsafatEx("فلزِمَنا جميعًا وعيد ربنا، إنا لذائقو العذاب، نحن وأنتم، بما قدمنا من ذنوبنا ومعاصينا في الدنيا."));
        alsafatExes.add(new AlsafatEx("فَأَغْوَيْنَاكُمْ إِنَّا كُنَّا غَاوِينَ (32)"));
        alsafatExes.add(new AlsafatEx("فأضللناكم عن سبيل الله والإيمان به، إنا كنا ضالين من قبلكم، فهلكنا; بسبب كفرنا، وأهلكناكم معنا."));
        alsafatExes.add(new AlsafatEx("فَإِنَّهُمْ يَوْمَئِذٍ فِي الْعَذَابِ مُشْتَرِكُونَ (33)"));
        alsafatExes.add(new AlsafatEx("فإن الأتباع والمتبوعين مشتركون يوم القيامة في العذاب، كما اشتركوا في الدنيا في معصية الله."));
        alsafatExes.add(new AlsafatEx("إِنَّا كَذَلِكَ نَفْعَلُ بِالْمُجْرِمِينَ (34)"));
        alsafatExes.add(new AlsafatEx("إنا هكذا نفعل بالذين اختاروا معاصي الله في الدنيا على طاعته، فنذيقهم العذاب الأليم."));
        alsafatExes.add(new AlsafatEx("إِنَّهُمْ كَانُوا إِذَا قِيلَ لَهُمْ لَا إِلَهَ إِلَّا اللَّهُ يَسْتَكْبِرُونَ (35)"));
        alsafatExes.add(new AlsafatEx("إن أولئك المشركين كانوا في الدنيا إذا قيل لهم: لا إله إلا الله، ودعوا إليها، وأُمروا بترك ما ينافيها، يستكبرون عنها وعلى من جاء بها."));
        alsafatExes.add(new AlsafatEx("وَيَقُولُونَ أَئِنَّا لَتَارِكُو آلِهَتِنَا لِشَاعِرٍ مَجْنُونٍ (36)"));
        alsafatExes.add(new AlsafatEx("ويقولون: أنترك عبادة آلهتنا لقول رجل شاعر مجنون؟ يعنون رسول الله صلى الله عليه وسلم."));
        alsafatExes.add(new AlsafatEx("بَلْ جَاءَ بِالْحَقِّ وَصَدَّقَ الْمُرْسَلِينَ (37)"));
        alsafatExes.add(new AlsafatEx("كذَبوا، ما محمد كما وصفوه به، بل جاء بالقرآن والتوحيد، وصدَّق المرسلين فيما أخبروا به عنه من شرع الله وتوحيده."));
        alsafatExes.add(new AlsafatEx("إِنَّكُمْ لَذَائِقُو الْعَذَابِ الْأَلِيمِ (38)"));
        alsafatExes.add(new AlsafatEx("إنكم -أيها المشركون- بقولكم وكفركم وتكذيبكم لذائقو العذاب الأليم الموجع."));
        alsafatExes.add(new AlsafatEx("وَمَا تُجْزَوْنَ إِلَّا مَا كُنْتُمْ تَعْمَلُونَ (39)"));
        alsafatExes.add(new AlsafatEx("وما تجزون في الآخرة إلا بما كنتم تعملونه في الدنيا من المعاصي."));
        alsafatExes.add(new AlsafatEx("إِلَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ (40)"));
        alsafatExes.add(new AlsafatEx("إلا عباد الله تعالى الذين أخلصوا له في عبادته، فأخلصهم واختصهم برحمته؛ فإنهم ناجون من العذاب الأليم."));
        alsafatExes.add(new AlsafatEx("أُولَئِكَ لَهُمْ رِزْقٌ مَعْلُومٌ (41)"));
        alsafatExes.add(new AlsafatEx("أولئك المخلصون لهم في الجنة رزق معلوم لا ينقطع."));
        alsafatExes.add(new AlsafatEx("فَوَاكِهُ وَهُمْ مُكْرَمُونَ (42)"));
        alsafatExes.add(new AlsafatEx("ذلك الرزق فواكه متنوعة، وهم مكرمون بكرامة الله."));
        alsafatExes.add(new AlsafatEx("فِي جَنَّاتِ النَّعِيمِ (43)"));
        alsafatExes.add(new AlsafatEx("لهم في جنات النعيم الدائم."));
        alsafatExes.add(new AlsafatEx("عَلَى سُرُرٍ مُتَقَابِلِينَ (44)"));
        alsafatExes.add(new AlsafatEx("ومن كرامتهم عند ربهم وإكرام بعضهم بعضًا أنهم على سرر متقابلين فيما بينهم."));
        alsafatExes.add(new AlsafatEx("يُطَافُ عَلَيْهِمْ بِكَأْسٍ مِنْ مَعِينٍ (45)"));
        alsafatExes.add(new AlsafatEx("يدار عليهم في مجالسهم بكؤوس خمر، من أنهار جارية، لا يخافون انقطاعها."));
        alsafatExes.add(new AlsafatEx("بَيْضَاءَ لَذَّةٍ لِلشَّارِبِينَ (46)"));
        alsafatExes.add(new AlsafatEx("بيضاء في لونها، لذيذة في شربها."));
        alsafatExes.add(new AlsafatEx("لَا فِيهَا غَوْلٌ وَلَا هُمْ عَنْهَا يُنْزَفُونَ (47)"));
        alsafatExes.add(new AlsafatEx("ليس فيها أذى للجسم ولا للعقل."));
        alsafatExes.add(new AlsafatEx("وَعِنْدَهُمْ قَاصِرَاتُ الطَّرْفِ عِينٌ (48)"));
        alsafatExes.add(new AlsafatEx("وعندهم في مجالسهم نساء عفيفات، لا ينظرن إلى غير أزواجهن حسان الأعين."));
        alsafatExes.add(new AlsafatEx("كَأَنَّهُنَّ بَيْضٌ مَكْنُونٌ (49)"));
        alsafatExes.add(new AlsafatEx("كأنهن بَيْض مصون لم تمسه الأيدي."));
        alsafatExes.add(new AlsafatEx("فَأَقْبَلَ بَعْضُهُمْ عَلَى بَعْضٍ يَتَسَاءَلُونَ (50)"));
        alsafatExes.add(new AlsafatEx("فأقبل بعضهم على بعض يتساءلون عن أحوالهم في الدنيا وما كانوا يعانون فيها، وما أنعم الله به عليهم في الجنة، وهذا من تمام الأنس."));
        alsafatExes.add(new AlsafatEx("قَالَ قَائِلٌ مِنْهُمْ إِنِّي كَانَ لِي قَرِينٌ (51)"));
        alsafatExes.add(new AlsafatEx("قال قائل من أهل الجنة: لقد كان لي في الدنيا صاحب ملازم لي."));
        alsafatExes.add(new AlsafatEx("يَقُولُ أَإِنَّكَ لَمِنَ الْمُصَدِّقِينَ (52)"));
        alsafatExes.add(new AlsafatEx("يقول: كيف تصدِّق بالبعث الذي هو في غاية الاستغراب؟"));
        alsafatExes.add(new AlsafatEx("أَإِذَا مِتْنَا وَكُنَّا تُرَابًا وَعِظَامًا أَإِنَّا لَمَدِينُونَ (53)"));
        alsafatExes.add(new AlsafatEx("أإذا متنا وتمزقنا وصرنا ترابًا وعظامًا، نُبعث ونُحاسب ونُجازى بأعمالنا؟"));
        alsafatExes.add(new AlsafatEx("قَالَ هَلْ أَنْتُمْ مُطَّلِعُونَ (54)"));
        alsafatExes.add(new AlsafatEx("قال هذا المؤمن الذي أُدخل الجنة لأصحابه: هل أنتم مُطَّلعون لنرى مصير ذلك القرين؟"));
        alsafatExes.add(new AlsafatEx("فَاطَّلَعَ فَرَآهُ فِي سَوَاءِ الْجَحِيمِ (55)"));
        alsafatExes.add(new AlsafatEx("فاطلع فرأى قرينه في وسط النار."));
        alsafatExes.add(new AlsafatEx("قَالَ تَاللَّهِ إِنْ كِدْتَ لَتُرْدِينِ (56)"));
        alsafatExes.add(new AlsafatEx("قال المؤمن لقرينه المنكر للبعث: لقد قاربت أن تهلكني بصدك إياي عن الإيمان لو أطعتك."));
        alsafatExes.add(new AlsafatEx("وَلَوْلَا نِعْمَةُ رَبِّي لَكُنْتُ مِنَ الْمُحْضَرِينَ (57)"));
        alsafatExes.add(new AlsafatEx("ولولا فضل ربي بهدايتي إلى الإيمان وتثبيتي عليه، لكنت من المحضرين في العذاب معك."));
        alsafatExes.add(new AlsafatEx("أَفَمَا نَحْنُ بِمَيِّتِينَ (58)"));
        alsafatExes.add(new AlsafatEx("أحقًا أننا مخلَّدون منعَّمون."));
        alsafatExes.add(new AlsafatEx("إِلَّا مَوْتَتَنَا الْأُولَى وَمَا نَحْنُ بِمُعَذَّبِينَ (59)"));
        alsafatExes.add(new AlsafatEx("فما نحن بميتين إلا موتتنا الأولى في الدنيا، وما نحن بمعذَّبين بعد دخولنا الجنة؟"));
        alsafatExes.add(new AlsafatEx("إِنَّ هَذَا لَهُوَ الْفَوْزُ الْعَظِيمُ (60)"));
        alsafatExes.add(new AlsafatEx("إنَّ ما نحن فيه من نعيم لهُوَ الظَّفَر العظيم."));
        alsafatExes.add(new AlsafatEx("لِمِثْلِ هَذَا فَلْيَعْمَلِ الْعَامِلُونَ (61)"));
        alsafatExes.add(new AlsafatEx("لمثل هذا النعيم الكامل، والخلود الدائم، والفوز العظيم، فليعمل العاملون في الدنيا; ليصيروا إليه في الآخرة."));
        alsafatExes.add(new AlsafatEx("أَذَلِكَ خَيْرٌ نُزُلًا أَمْ شَجَرَةُ الزَّقُّومِ (62)"));
        alsafatExes.add(new AlsafatEx("أذلك الذي سبق وصفه مِن نعيم الجنة خير ضيافة وعطاء من الله، أم شجرة الزقوم الخبيثة الملعونة، طعام أهل النار؟"));
        alsafatExes.add(new AlsafatEx("إِنَّا جَعَلْنَاهَا فِتْنَةً لِلظَّالِمِينَ (63)"));
        alsafatExes.add(new AlsafatEx("إنا جعلناها فتنة افتتن بها الظالمون لأنفسهم بالكفر والمعاصي، وقالوا مستنكرين: إن صاحبكم ينبئكم أن في النار شجرة، والنار تأكل الشجر."));
        alsafatExes.add(new AlsafatEx("إِنَّهَا شَجَرَةٌ تَخْرُجُ فِي أَصْلِ الْجَحِيمِ (64)"));
        alsafatExes.add(new AlsafatEx("إنها شجرة تنبت في قعر جهنم."));
        alsafatExes.add(new AlsafatEx("طَلْعُهَا كَأَنَّهُ رُءُوسُ الشَّيَاطِينِ (65)"));
        alsafatExes.add(new AlsafatEx("ثمرها قبيح المنظر كأنه رؤوس الشياطين، فإذا كانت كذلك فلا تَسْألْ بعد هذا عن طعمها."));
        alsafatExes.add(new AlsafatEx("فَإِنَّهُمْ لَآكِلُونَ مِنْهَا فَمَالِئُونَ مِنْهَا الْبُطُونَ (66)"));
        alsafatExes.add(new AlsafatEx("فإن المشركين لآكلون من تلك الشجرة فمالئون منها بطونهم."));
        alsafatExes.add(new AlsafatEx("ثُمَّ إِنَّ لَهُمْ عَلَيْهَا لَشَوْبًا مِنْ حَمِيمٍ (67)"));
        alsafatExes.add(new AlsafatEx("ثم إنهم بعد الأكل منها لشاربون شرابًا خليطًا قبيحًا حارًّا."));
        alsafatExes.add(new AlsafatEx("ثُمَّ إِنَّ مَرْجِعَهُمْ لَإِلَى الْجَحِيمِ (68)"));
        alsafatExes.add(new AlsafatEx("ثم إن مردَّهم بعد هذا العذاب إلى عذاب النار."));
        alsafatExes.add(new AlsafatEx("إِنَّهُمْ أَلْفَوْا آبَاءَهُمْ ضَالِّينَ (69)"));
        alsafatExes.add(new AlsafatEx("إنهم وجدوا آباءهم على الشرك والضلال."));
        alsafatExes.add(new AlsafatEx("فَهُمْ عَلَى آثَارِهِمْ يُهْرَعُونَ (70)"));
        alsafatExes.add(new AlsafatEx("فسارعوا إلى متابعتهم على ذلك."));
        alsafatExes.add(new AlsafatEx("وَلَقَدْ ضَلَّ قَبْلَهُمْ أَكْثَرُ الْأَوَّلِينَ (71)"));
        alsafatExes.add(new AlsafatEx("ولقد ضلَّ عن الحق قبل قومك -أيها الرسول- أكثر الأمم السابقة."));
        alsafatExes.add(new AlsafatEx("وَلَقَدْ أَرْسَلْنَا فِيهِمْ مُنْذِرِينَ (72)"));
        alsafatExes.add(new AlsafatEx("ولقد أرسلنا في تلك الأمم مرسلين أنذروهم بالعذاب فكفروا."));
        alsafatExes.add(new AlsafatEx("فَانْظُرْ كَيْفَ كَانَ عَاقِبَةُ الْمُنْذَرِينَ (73)"));
        alsafatExes.add(new AlsafatEx("فتأمَّل كيف كانت نهاية تلك الأمم التي أنذرت، فكفرت؟ فقد عُذِّبت، وصارت للناس عبرة."));
        alsafatExes.add(new AlsafatEx("إِلَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ (74)"));
        alsafatExes.add(new AlsafatEx("إلا عباد الله الذين أخلصهم الله، وخصَّهم برحمته لإخلاصهم له."));
        alsafatExes.add(new AlsafatEx("وَلَقَدْ نَادَانَا نُوحٌ فَلَنِعْمَ الْمُجِيبُونَ (75)"));
        alsafatExes.add(new AlsafatEx("ولقد نادانا نبينا نوح; لننصره على قومه، فلنعم المجيبون له نحن."));
        alsafatExes.add(new AlsafatEx("وَنَجَّيْنَاهُ وَأَهْلَهُ مِنَ الْكَرْبِ الْعَظِيمِ (76)"));
        alsafatExes.add(new AlsafatEx("ونجيناه وأهله والمؤمنين معه مِن أذى المشركين، ومن الغرق بالطوفان العظيم."));
        alsafatExes.add(new AlsafatEx("وَجَعَلْنَا ذُرِّيَّتَهُ هُمُ الْبَاقِينَ (77)"));
        alsafatExes.add(new AlsafatEx("وجعلنا ذرية نوح هم الباقين بعد غرق قومه."));
        alsafatExes.add(new AlsafatEx("وَتَرَكْنَا عَلَيْهِ فِي الْآخِرِينَ (78)"));
        alsafatExes.add(new AlsafatEx("وأبقينا له ذِكْرًا جميلا وثناءً حسنًا فيمن جاء بعده من الناس يذكرونه به."));
        alsafatExes.add(new AlsafatEx("سَلَامٌ عَلَى نُوحٍ فِي الْعَالَمِينَ (79)"));
        alsafatExes.add(new AlsafatEx("أمان لنوح وسلامة له من أن يُذْكر بسوء في الآخِرين، بل تُثني عليه الأجيال من بعده."));
        alsafatExes.add(new AlsafatEx("إِنَّا كَذَلِكَ نَجْزِي الْمُحْسِنِينَ (80)"));
        alsafatExes.add(new AlsafatEx("مثل جزاء نوح نجزي كلَّ مَن أحسن من العباد في طاعة الله."));
        alsafatExes.add(new AlsafatEx("إِنَّهُ مِنْ عِبَادِنَا الْمُؤْمِنِينَ (81)"));
        alsafatExes.add(new AlsafatEx("إن نوحًا من عبادنا المصدقين المخلصين العاملين بأوامر الله."));
        alsafatExes.add(new AlsafatEx("ثُمَّ أَغْرَقْنَا الْآخَرِينَ (82)"));
        alsafatExes.add(new AlsafatEx("ثم أغرقنا الآخرين المكذبين من قومه بالطوفان، فلم تبق منهم عين تَطْرِف."));
        alsafatExes.add(new AlsafatEx("وَإِنَّ مِنْ شِيعَتِهِ لَإِبْرَاهِيمَ (83)"));
        alsafatExes.add(new AlsafatEx("وإنَّ من أشياع نوح على منهاجه وملَّته نبيَّ الله إبراهيم."));
        alsafatExes.add(new AlsafatEx("إِذْ جَاءَ رَبَّهُ بِقَلْبٍ سَلِيمٍ (84)"));
        alsafatExes.add(new AlsafatEx("حين جاء ربه بقلب بريء من كل اعتقاد باطل وخُلُق ذميم."));
        alsafatExes.add(new AlsafatEx("إِذْ قَالَ لِأَبِيهِ وَقَوْمِهِ مَاذَا تَعْبُدُونَ (85)"));
        alsafatExes.add(new AlsafatEx("حين قال لأبيه وقومه منكرًا عليهم: ما الذي تعبدونه من دون الله؟"));
        alsafatExes.add(new AlsafatEx("أَئِفْكًا آلِهَةً دُونَ اللَّهِ تُرِيدُونَ (86)"));
        alsafatExes.add(new AlsafatEx("أتريدون آلهة مختلَقَة تعبدونها، وتتركون عبادة الله المستحق للعبادة وحده؟"));
        alsafatExes.add(new AlsafatEx("فَمَا ظَنُّكُمْ بِرَبِّ الْعَالَمِينَ (87)"));
        alsafatExes.add(new AlsafatEx("فما ظنكم برب العالمين أنه فاعل بكم إذا أشركتم به وعبدتم معه غيره؟"));
        alsafatExes.add(new AlsafatEx("فَنَظَرَ نَظْرَةً فِي النُّجُومِ (88)"));
        alsafatExes.add(new AlsafatEx("فنظر إبراهيم نظرة في النجوم -على عادة قومه في ذلك- متفكرًا فيما يعتذر به عن الخروج معهم إلى أعيادهم."));
        alsafatExes.add(new AlsafatEx("فَقَالَ إِنِّي سَقِيمٌ (89)"));
        alsafatExes.add(new AlsafatEx("فقال لهم: إني مريض. وهذا تعريض منه."));
        alsafatExes.add(new AlsafatEx("فَتَوَلَّوْا عَنْهُ مُدْبِرِينَ (90)"));
        alsafatExes.add(new AlsafatEx("فتركوه وراء ظهورهم."));
        alsafatExes.add(new AlsafatEx("فَرَاغَ إِلَى آلِهَتِهِمْ فَقَالَ أَلَا تَأْكُلُونَ (91)"));
        alsafatExes.add(new AlsafatEx("فمال مسرعًا إلى أصنام قومه فقال مستهزئًا بها: ألا تأكلون هذا الطعام الذي يقدمه لكم سدنتكم؟"));
        alsafatExes.add(new AlsafatEx("مَا لَكُمْ لَا تَنْطِقُونَ (92)"));
        alsafatExes.add(new AlsafatEx("ما لكم لا تنطقون ولا تجيبون مَن يسألكم؟"));
        alsafatExes.add(new AlsafatEx("فَرَاغَ عَلَيْهِمْ ضَرْبًا بِالْيَمِينِ (93)"));
        alsafatExes.add(new AlsafatEx("فأقبل على آلهتهم يضربها ويكسِّرها بيده اليمني; ليثبت لقومه خطأ عبادتهم لها."));
        alsafatExes.add(new AlsafatEx("فَأَقْبَلُوا إِلَيْهِ يَزِفُّونَ (94)"));
        alsafatExes.add(new AlsafatEx("فأقبلوا إليه يَعْدُون مسرعين غاضبين."));
        alsafatExes.add(new AlsafatEx("قَالَ أَتَعْبُدُونَ مَا تَنْحِتُونَ (95)"));
        alsafatExes.add(new AlsafatEx("فلقيهم إبراهيم بثبات قائلا كيف تعبدون أصنامًا تنحتونها أنتم، وتصنعونها بأيديكم."));
        alsafatExes.add(new AlsafatEx("وَاللَّهُ خَلَقَكُمْ وَمَا تَعْمَلُونَ (96)"));
        alsafatExes.add(new AlsafatEx("وتتركون عبادة ربكم الذي خلقكم، وخلق عملكم؟"));
        alsafatExes.add(new AlsafatEx("قَالُوا ابْنُوا لَهُ بُنْيَانًا فَأَلْقُوهُ فِي الْجَحِيمِ (97)"));
        alsafatExes.add(new AlsafatEx("فلما قامت عليهم الحجة لجؤوا إلى القوة، وقالوا: ابنوا له بنيانًا واملؤوه حطبًا، ثم ألقوه فيه."));
        alsafatExes.add(new AlsafatEx("فَأَرَادُوا بِهِ كَيْدًا فَجَعَلْنَاهُمُ الْأَسْفَلِينَ (98)"));
        alsafatExes.add(new AlsafatEx("فأراد قوم إبراهيم به كيدًا لإهلاكه، فجعلناهم المقهورين المغلوبين، وردَّ الله كيدهم في نحورهم، وجعل النار على إبراهيم بردًا وسلامًا."));
        alsafatExes.add(new AlsafatEx("وَقَالَ إِنِّي ذَاهِبٌ إِلَى رَبِّي سَيَهْدِينِ (99)"));
        alsafatExes.add(new AlsafatEx("وقال إبراهيم: إني مهاجر إلى ربي من بلد قومي إلى حيث أتمكن من عبادة ربي; فإنه سيدلني على الخير في ديني ودنياي."));
        alsafatExes.add(new AlsafatEx("رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ (100)"));
        alsafatExes.add(new AlsafatEx("رب أعطني ولدًا صالحًا."));
        alsafatExes.add(new AlsafatEx("فَبَشَّرْنَاهُ بِغُلَامٍ حَلِيمٍ (101)"));
        alsafatExes.add(new AlsafatEx("فأجبنا له دعوته، وبشَّرناه بغلام حليم، أي: يكون حليمًا في كبره، وهو إسماعيل."));
        alsafatExes.add(new AlsafatEx("فَلَمَّا بَلَغَ مَعَهُ السَّعْيَ قَالَ يَابُنَيَّ إِنِّي أَرَى فِي الْمَنَامِ أَنِّي أَذْبَحُكَ فَانْظُرْ مَاذَا تَرَى قَالَ يَاأَبَتِ افْعَلْ مَا تُؤْمَرُ سَتَجِدُنِي إِنْ شَاءَ اللَّهُ مِنَ الصَّابِرِينَ (102)"));
        alsafatExes.add(new AlsafatEx("فلما كَبِر إسماعيل ومشى مع أبيه قال له أبوه: إني أرى في المنام أني أذبحك، فما رأيك؟ (ورؤيا الأنبياء حق) فقال إسماعيل مُرْضيًا ربه، بارًّا بوالده، معينًا له على طاعة الله: أمض ما أمرك الله به مِن ذبحي، ستجدني -إن شاء الله- صابرًا طائعًا محتسبًا."));
        alsafatExes.add(new AlsafatEx("فَلَمَّا أَسْلَمَا وَتَلَّهُ لِلْجَبِينِ (103)"));
        alsafatExes.add(new AlsafatEx("فلما استسلما لأمر الله وانقادا له، وألقى إبراهيم ابنه على جبينه -وهو جانب الجبهة- على الأرض؛ ليذبحه."));
        alsafatExes.add(new AlsafatEx("وَنَادَيْنَاهُ أَنْ يَاإِبْرَاهِيمُ (104)"));
        alsafatExes.add(new AlsafatEx("ونادينا إبراهيم في تلك الحالة العصيبة: أن يا إبراهيم."));
        alsafatExes.add(new AlsafatEx("قَدْ صَدَّقْتَ الرُّؤْيَا إِنَّا كَذَلِكَ نَجْزِي الْمُحْسِنِينَ (105)"));
        alsafatExes.add(new AlsafatEx("قد فعلتَ ما أُمرت به وصَدَّقْتَ رؤياك، إنا كما جزيناك على تصديقك نجزي الذين أحسنوا مثلك، فنخلِّصهم من الشدائد في الدنيا والآخرة."));
        alsafatExes.add(new AlsafatEx("إِنَّ هَذَا لَهُوَ الْبَلَاءُ الْمُبِينُ (106)"));
        alsafatExes.add(new AlsafatEx("إن الأمر بذبح ابنك هو الابتلاء الشاق الذي أبان عن صدق إيمانك."));
        alsafatExes.add(new AlsafatEx("وَفَدَيْنَاهُ بِذِبْحٍ عَظِيمٍ (107)"));
        alsafatExes.add(new AlsafatEx("واستنقذنا إسماعيل، فجعلنا بديلا عنه كبشًا عظيمًا."));
        alsafatExes.add(new AlsafatEx("وَتَرَكْنَا عَلَيْهِ فِي الْآخِرِينَ (108)"));
        alsafatExes.add(new AlsafatEx("وأبقينا لإبراهيم ثناءً حسنًا في الأمم بعده."));
        alsafatExes.add(new AlsafatEx("سَلَامٌ عَلَى إِبْرَاهِيمَ (109)"));
        alsafatExes.add(new AlsafatEx("تحيةٌ لإبراهيم من عند الله، ودعاءٌ له بالسلامة من كل آفة."));
        alsafatExes.add(new AlsafatEx("كَذَلِكَ نَجْزِي الْمُحْسِنِينَ (110)"));
        alsafatExes.add(new AlsafatEx("كما جزينا إبراهيم على طاعته لنا وامتثاله أمرنا، نجزي المحسنين من عبادنا."));
        alsafatExes.add(new AlsafatEx("إِنَّهُ مِنْ عِبَادِنَا الْمُؤْمِنِينَ (111)"));
        alsafatExes.add(new AlsafatEx("إنه من عبادنا المؤمنين الذين أعطَوا العبودية حقها."));
        alsafatExes.add(new AlsafatEx("وَبَشَّرْنَاهُ بِإِسْحَاقَ نَبِيًّا مِنَ الصَّالِحِينَ (112)"));
        alsafatExes.add(new AlsafatEx("وبشَّرنا إبراهيم بولده إسحاق نبيًّا من الصالحين; جزاء له على صبره ورضاه بأمر ربه، وطاعته له."));
        alsafatExes.add(new AlsafatEx("وَبَارَكْنَا عَلَيْهِ وَعَلَى إِسْحَاقَ وَمِنْ ذُرِّيَّتِهِمَا مُحْسِنٌ وَظَالِمٌ لِنَفْسِهِ مُبِينٌ (113)"));
        alsafatExes.add(new AlsafatEx("وأنزلنا عليهما البركة. ومِن ذريتهما من هو مطيع لربه، محسن لنفسه، ومَن هو ظالم لها ظلمًا بيِّنًا بكفره ومعصيته."));
        alsafatExes.add(new AlsafatEx("وَلَقَدْ مَنَنَّا عَلَى مُوسَى وَهَارُونَ (114)"));
        alsafatExes.add(new AlsafatEx("ولقد مننَّا على موسى وهارون بالنبوة والرسالة."));
        alsafatExes.add(new AlsafatEx("وَنَجَّيْنَاهُمَا وَقَوْمَهُمَا مِنَ الْكَرْبِ الْعَظِيمِ (115)"));
        alsafatExes.add(new AlsafatEx("ونجيناهما وقومهما من الغرق، وما كانوا فيه من عبودية ومَذلَّة."));
        alsafatExes.add(new AlsafatEx("وَنَصَرْنَاهُمْ فَكَانُوا هُمُ الْغَالِبِينَ (116)"));
        alsafatExes.add(new AlsafatEx("ونصرناهم، فكانت لهم العزة والنصرة والغلبة على فرعون وآله."));
        alsafatExes.add(new AlsafatEx("وَآتَيْنَاهُمَا الْكِتَابَ الْمُسْتَبِينَ (117)"));
        alsafatExes.add(new AlsafatEx("وآتيناهما التوراة البينة."));
        alsafatExes.add(new AlsafatEx("وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ (118)"));
        alsafatExes.add(new AlsafatEx("وهديناهما الطريق المستقيم الذي لا اعوجاج فيه، وهو الإسلام دين الله الذي ابتعث به أنبياءه."));
        alsafatExes.add(new AlsafatEx("وَتَرَكْنَا عَلَيْهِمَا فِي الْآخِرِينَ (119)"));
        alsafatExes.add(new AlsafatEx("وأبقينا لهما ثناءً حسنًا وذكرًا جميلا فيمن بعدهما."));
        alsafatExes.add(new AlsafatEx("سَلَامٌ عَلَى مُوسَى وَهَارُونَ (120)"));
        alsafatExes.add(new AlsafatEx("تحيةٌ لموسى وهارون من عند الله، وثناءٌ ودعاءٌ لهما بالسلامة من كل آفة."));
        alsafatExes.add(new AlsafatEx("إِنَّا كَذَلِكَ نَجْزِي الْمُحْسِنِينَ (121)"));
        alsafatExes.add(new AlsafatEx("كما جزيناهما الجزاء الحسن نجزي المحسنين من عبادنا المخلصين لنا بالصدق والإيمان والعمل."));
        alsafatExes.add(new AlsafatEx("إِنَّهُمَا مِنْ عِبَادِنَا الْمُؤْمِنِينَ (122)"));
        alsafatExes.add(new AlsafatEx("إنهما من عبادنا الراسخين في الإيمان."));
        alsafatExes.add(new AlsafatEx("وَإِنَّ إِلْيَاسَ لَمِنَ الْمُرْسَلِينَ (123)"));
        alsafatExes.add(new AlsafatEx("وإن عبدنا إلياس لمن الذين أكرمناهم بالنبوة والرسالة."));
        alsafatExes.add(new AlsafatEx("إِذْ قَالَ لِقَوْمِهِ أَلَا تَتَّقُونَ (124)"));
        alsafatExes.add(new AlsafatEx("ذ قال لقومه من بني إسرائيل: اتقوا الله وحده وخافوه."));
        alsafatExes.add(new AlsafatEx("أَتَدْعُونَ بَعْلًا وَتَذَرُونَ أَحْسَنَ الْخَالِقِينَ (125)"));
        alsafatExes.add(new AlsafatEx("ولا تشركوا معه غيره، كيف تعبدون صنمًا، وتتركون عبادة الله أحسن الخالقين -المتصف بأحسن الصفات وأكملها فلا تعبدونه! -."));
        alsafatExes.add(new AlsafatEx("اللَّهَ رَبَّكُمْ وَرَبَّ آبَائِكُمُ الْأَوَّلِينَ (126)"));
        alsafatExes.add(new AlsafatEx("الله ربكم الذي خلقكم، وخلق آباءكم الماضين قبلكم؟"));
        alsafatExes.add(new AlsafatEx("فَكَذَّبُوهُ فَإِنَّهُمْ لَمُحْضَرُونَ (127)"));
        alsafatExes.add(new AlsafatEx("فكذب قوم إلياس نبيهم، فليجمعنهم الله يوم القيامة للحساب والعقاب."));
        alsafatExes.add(new AlsafatEx("إِلَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ (128)"));
        alsafatExes.add(new AlsafatEx("إلا عباد الله الذين أخلصوا دينهم لله، فإنهم ناجون من عذابه."));
        alsafatExes.add(new AlsafatEx("وَتَرَكْنَا عَلَيْهِ فِي الْآخِرِينَ (129)"));
        alsafatExes.add(new AlsafatEx("وجعلنا لإلياس ثناءً جميلا في الأمم بعده."));
        alsafatExes.add(new AlsafatEx("سَلَامٌ عَلَى إِلْ يَاسِينَ (130)"));
        alsafatExes.add(new AlsafatEx("تحية من الله، وثناءٌ على إلياس."));
        alsafatExes.add(new AlsafatEx("إِنَّا كَذَلِكَ نَجْزِي الْمُحْسِنِينَ (131)."));
        alsafatExes.add(new AlsafatEx("وكما جزينا إلياس الجزاء الحسن على طاعته، نجزي المحسنين من عبادنا المؤمنين."));
        alsafatExes.add(new AlsafatEx("إِنَّهُ مِنْ عِبَادِنَا الْمُؤْمِنِينَ (132)"));
        alsafatExes.add(new AlsafatEx("إنه من عباد الله المؤمنين المخلصين له العاملين بأوامره."));
        alsafatExes.add(new AlsafatEx("وَإِنَّ لُوطًا لَمِنَ الْمُرْسَلِينَ (133)"));
        alsafatExes.add(new AlsafatEx("وإن عبدنا لوطًا اصطفيناه، فجعلناه من المرسلين."));
        alsafatExes.add(new AlsafatEx("إِذْ نَجَّيْنَاهُ وَأَهْلَهُ أَجْمَعِينَ (134)"));
        alsafatExes.add(new AlsafatEx("إذ نجيناه وأهله أجمعين من العذاب."));
        alsafatExes.add(new AlsafatEx("إِلَّا عَجُوزًا فِي الْغَابِرِينَ (135)"));
        alsafatExes.add(new AlsafatEx("إلا عجوزًا هَرِمة، هي زوجته، هلكت مع الذين هلكوا من قومها لكفرها."));
        alsafatExes.add(new AlsafatEx("ثُمَّ دَمَّرْنَا الْآخَرِينَ (136)"));
        alsafatExes.add(new AlsafatEx("ثم أهلكنا الباقين المكذبين من قومه."));
        alsafatExes.add(new AlsafatEx("وَإِنَّكُمْ لَتَمُرُّونَ عَلَيْهِمْ مُصْبِحِينَ (137)"));
        alsafatExes.add(new AlsafatEx("وإنكم -يا أهل «مكة» - لتمرون فى أسفاركم على منازل قوم لوط وآثارهم وقت الصباح."));
        alsafatExes.add(new AlsafatEx("وَبِاللَّيْلِ أَفَلَا تَعْقِلُونَ (138)"));
        alsafatExes.add(new AlsafatEx("وتمرون عليها ليلا. أفلا تعقلون، فتخافوا أن يصيبكم مثل ما أصابهم؟"));
        alsafatExes.add(new AlsafatEx("وَإِنَّ يُونُسَ لَمِنَ الْمُرْسَلِينَ (139)"));
        alsafatExes.add(new AlsafatEx("وإن عبدنا يونس اصطفيناه وجعلناه من المرسلين."));
        alsafatExes.add(new AlsafatEx("إِذْ أَبَقَ إِلَى الْفُلْكِ الْمَشْحُونِ (140)"));
        alsafatExes.add(new AlsafatEx("إذ هرب من بلده غاضبًا على قومه، وركب سفينة مملوءة ركابًا وأمتعة."));
        alsafatExes.add(new AlsafatEx("فَسَاهَمَ فَكَانَ مِنَ الْمُدْحَضِينَ (141)"));
        alsafatExes.add(new AlsafatEx("وأحاطت بها الأمواج العظيمة، فاقترع ركاب السفينة لتخفيف الحمولة خوف الغرق، فكان يونس من المغلوبين."));
        alsafatExes.add(new AlsafatEx("فَالْتَقَمَهُ الْحُوتُ وَهُوَ مُلِيمٌ (142)"));
        alsafatExes.add(new AlsafatEx("فأُلقي في البحر، فابتلعه الحوت، ويونس عليه السلام آتٍ بما يُلام عليه."));
        alsafatExes.add(new AlsafatEx("فَلَوْلَا أَنَّهُ كَانَ مِنَ الْمُسَبِّحِينَ (143)"));
        alsafatExes.add(new AlsafatEx("فلولا ما تقدَّم له من كثرة العبادة والعمل الصالح قبل وقوعه في بطن الحوت، وتسبيحه، وهو في بطن الحوت بقوله: {لا إِلَهَ إِلا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ} ؛ لمكث في بطن الحوت، وصار له قبرًا إلى يوم القيامة."));
        alsafatExes.add(new AlsafatEx("فَنَبَذْنَاهُ بِالْعَرَاءِ وَهُوَ سَقِيمٌ (145)"));
        alsafatExes.add(new AlsafatEx("فطرحناه من بطن الحوت، وألقيناه في أرض خالية عارية من الشجر والبناء، وهو ضعيف البدن."));
        alsafatExes.add(new AlsafatEx("وَأَنْبَتْنَا عَلَيْهِ شَجَرَةً مِنْ يَقْطِينٍ (146)"));
        alsafatExes.add(new AlsafatEx("وأنبتنا عليه شجرة من القَرْع تظلُّه، وينتفع بها."));
        alsafatExes.add(new AlsafatEx("وَأَرْسَلْنَاهُ إِلَى مِائَةِ أَلْفٍ أَوْ يَزِيدُونَ (147)"));
        alsafatExes.add(new AlsafatEx("وأرسلناه إلى مائة ألف من قومه بل يزيدون."));
        alsafatExes.add(new AlsafatEx("فَآمَنُوا فَمَتَّعْنَاهُمْ إِلَى حِينٍ (148)"));
        alsafatExes.add(new AlsafatEx("فصدَّقوا وعملوا بما جاء به، فمتعناهم بحياتهم إلى وقت بلوغ آجالهم."));
        alsafatExes.add(new AlsafatEx("فَاسْتَفْتِهِمْ أَلِرَبِّكَ الْبَنَاتُ وَلَهُمُ الْبَنُونَ (149)"));
        alsafatExes.add(new AlsafatEx("فاسأل -أيها الرسول- قومك: كيف جعلوا لله البنات اللاتي يكرهونهنَّ، ولأنفسهم البنين الذين يريدونهم؟"));
        alsafatExes.add(new AlsafatEx("أَمْ خَلَقْنَا الْمَلَائِكَةَ إِنَاثًا وَهُمْ شَاهِدُونَ (150)"));
        alsafatExes.add(new AlsafatEx("واسألهم أخَلَقْنا الملائكة إناثًا، وهم حاضرون؟"));
        alsafatExes.add(new AlsafatEx("أَلَا إِنَّهُمْ مِنْ إِفْكِهِمْ لَيَقُولُونَ (151)"));
        alsafatExes.add(new AlsafatEx("وإنَّ مِن كذبهم قولهم."));
        alsafatExes.add(new AlsafatEx("وَلَدَ اللَّهُ وَإِنَّهُمْ لَكَاذِبُونَ (152)"));
        alsafatExes.add(new AlsafatEx("ولَد الله، وإنهم لكاذبون; لأنهم يقولون ما لا يعلمون."));
        alsafatExes.add(new AlsafatEx("أَصْطَفَى الْبَنَاتِ عَلَى الْبَنِينَ (153)"));
        alsafatExes.add(new AlsafatEx("لأي شيء يختار الله البنات دون البنين؟"));
        alsafatExes.add(new AlsafatEx("مَا لَكُمْ كَيْفَ تَحْكُمُونَ (154)"));
        alsafatExes.add(new AlsafatEx("بئس الحكم ما تحكمونه -أيها القوم- أن يكون لله البنات ولكم البنون، وأنتم لا ترضون البنات لأنفسكم."));
        alsafatExes.add(new AlsafatEx("أَفَلَا تَذَكَّرُونَ (155)"));
        alsafatExes.add(new AlsafatEx("أفلا تذكرون أنه لا يجوز ولا ينبغي أن يكون له ولد؟ تعالى الله عن ذلك علوًّا كبيرًا."));
        alsafatExes.add(new AlsafatEx("أَمْ لَكُمْ سُلْطَانٌ مُبِينٌ (156)"));
        alsafatExes.add(new AlsafatEx("بل ألكم حجة بيِّنة على قولكم وافترائكم؟"));
        alsafatExes.add(new AlsafatEx("فَأْتُوا بِكِتَابِكُمْ إِنْ كُنْتُمْ صَادِقِينَ (157)"));
        alsafatExes.add(new AlsafatEx("إن كانت لكم حجة في كتاب من عند الله فأتوا بها، إن كنتم صادقين في قولكم؟"));
        alsafatExes.add(new AlsafatEx("وَجَعَلُوا بَيْنَهُ وَبَيْنَ الْجِنَّةِ نَسَبًا وَلَقَدْ عَلِمَتِ الْجِنَّةُ إِنَّهُمْ لَمُحْضَرُونَ (158)"));
        alsafatExes.add(new AlsafatEx("وجعل المشركون بين الله والملائكة قرابة ونسبًا، ولقد علمت الملائكة أن المشركين محضرون للعذاب يوم القيامة."));
        alsafatExes.add(new AlsafatEx("سُبْحَانَ اللَّهِ عَمَّا يَصِفُونَ (159)"));
        alsafatExes.add(new AlsafatEx("تنزَّه الله عن كل ما لا يليق به ممَّا يصفه به الكافرون."));
        alsafatExes.add(new AlsafatEx("إِلَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ (160)"));
        alsafatExes.add(new AlsafatEx("لكن عباد الله المخلصين له في عبادته لا يصفونه إلا بما يليق بجلاله سبحانه."));
        alsafatExes.add(new AlsafatEx("فَإِنَّكُمْ وَمَا تَعْبُدُونَ (161)"));
        alsafatExes.add(new AlsafatEx("فإنكم -أيها المشركون بالله- وما تعبدون من دون الله من آلهة."));
        alsafatExes.add(new AlsafatEx("مَا أَنْتُمْ عَلَيْهِ بِفَاتِنِينَ (162)"));
        alsafatExes.add(new AlsafatEx("ما أنتم بمضلِّين أحدًا."));
        alsafatExes.add(new AlsafatEx("إِلَّا مَنْ هُوَ صَالِ الْجَحِيمِ (163)"));
        alsafatExes.add(new AlsafatEx("إلا مَن قدَّر الله عز وجل عليه أن يَصْلَى الجحيم؛ لكفره وظلمه."));
        alsafatExes.add(new AlsafatEx("وَمَا مِنَّا إِلَّا لَهُ مَقَامٌ مَعْلُومٌ (164)"));
        alsafatExes.add(new AlsafatEx("قالت الملائكة: وما منا أحدٌ إلا له مقام في السماء معلوم."));
        alsafatExes.add(new AlsafatEx("وَإِنَّا لَنَحْنُ الصَّافُّونَ (165)"));
        alsafatExes.add(new AlsafatEx("وإنا لنحن الواقفون صفوفًا في عبادة الله وطاعته."));
        alsafatExes.add(new AlsafatEx("وَإِنَّا لَنَحْنُ الْمُسَبِّحُونَ (166)"));
        alsafatExes.add(new AlsafatEx("وإنا لنحن المنزِّهون الله عن كل ما لا يليق به."));
        alsafatExes.add(new AlsafatEx("وَإِنْ كَانُوا لَيَقُولُونَ (167)"));
        alsafatExes.add(new AlsafatEx("وإن كفار «مكة» ليقولون قبل بعثتك -أيها الرسول-:"));
        alsafatExes.add(new AlsafatEx("لَوْ أَنَّ عِنْدَنَا ذِكْرًا مِنَ الْأَوَّلِينَ (168)"));
        alsafatExes.add(new AlsafatEx("لو جاءنا من الكتب والأنبياء ما جاء الأولين قبلنا."));
        alsafatExes.add(new AlsafatEx("لَكُنَّا عِبَادَ اللَّهِ الْمُخْلَصِينَ (169)"));
        alsafatExes.add(new AlsafatEx("لكنا عباد الله الصادقين في الإيمان، المخلَصين في العبادة."));
        alsafatExes.add(new AlsafatEx("فَكَفَرُوا بِهِ فَسَوْفَ يَعْلَمُونَ (170)"));
        alsafatExes.add(new AlsafatEx("فلما جاءهم ذكر الأولين، وعلم الآخرين، وأكمل الكتب، وأفضل الرسل، وهو محمد صلى الله عليه وسلم، كفروا به، فسوف يعلمون ما لهم من العذاب في الآخرة."));
        alsafatExes.add(new AlsafatEx("وَلَقَدْ سَبَقَتْ كَلِمَتُنَا لِعِبَادِنَا الْمُرْسَلِينَ (171)"));
        alsafatExes.add(new AlsafatEx("ولقد سبقت كلمتنا -التي لا مردَّ لها- لعبادنا المرسلين."));
        alsafatExes.add(new AlsafatEx("إِنَّهُمْ لَهُمُ الْمَنْصُورُونَ (172)"));
        alsafatExes.add(new AlsafatEx("أن لهم النصرة على أعدائهم بالحجة والقوة."));
        alsafatExes.add(new AlsafatEx("وَإِنَّ جُنْدَنَا لَهُمُ الْغَالِبُونَ (173)"));
        alsafatExes.add(new AlsafatEx("وأن جندنا المجاهدين في سبيلنا لهم الغالبون لأعدائهم في كل مقام باعتبار العاقبة والمآل."));
        alsafatExes.add(new AlsafatEx("فَتَوَلَّ عَنْهُمْ حَتَّى حِينٍ (174)"));
        alsafatExes.add(new AlsafatEx("فأعرض -أيها الرسول- عَمَّن عاند، ولم يقبل الحق حتى تنقضي المدة التي أمهلهم فيها، ويأتي أمر الله بعذابهم، وأنظرهم وارتقب ماذا يحل بهم من العذاب بمخالفتك؟"));
        alsafatExes.add(new AlsafatEx("وَأَبْصِرْهُمْ فَسَوْفَ يُبْصِرُونَ (175)"));
        alsafatExes.add(new AlsafatEx("فسوف يرون ما يحل بهم من عذاب الله."));
        alsafatExes.add(new AlsafatEx("أَفَبِعَذَابِنَا يَسْتَعْجِلُونَ (176)"));
        alsafatExes.add(new AlsafatEx("أفبنزول عذابنا بهم يستعجلونك أيها الرسول؟"));
        alsafatExes.add(new AlsafatEx(") فَإِذَا نَزَلَ بِسَاحَتِهِمْ فَسَاءَ صَبَاحُ الْمُنْذَرِينَ (177)"));
        alsafatExes.add(new AlsafatEx("فإذا نزل عذابنا بهم، فبئس الصباح صباحهم."));
        alsafatExes.add(new AlsafatEx("وَتَوَلَّ عَنْهُمْ حَتَّى حِينٍ (178)"));
        alsafatExes.add(new AlsafatEx("وأعرض عنهم حتى يأذن الله بعذابهم."));
        alsafatExes.add(new AlsafatEx("وَأَبْصِرْ فَسَوْفَ يُبْصِرُونَ (179)"));
        alsafatExes.add(new AlsafatEx("وأنظرهم فسوف يرون ما يحل بهم من العذاب والنكال."));
        alsafatExes.add(new AlsafatEx("سُبْحَانَ رَبِّكَ رَبِّ الْعِزَّةِ عَمَّا يَصِفُونَ (180)"));
        alsafatExes.add(new AlsafatEx("تنزَّه الله وتعالى رب العزة عما يصفه هؤلاء المفترون عليه."));
        alsafatExes.add(new AlsafatEx("وَسَلَامٌ عَلَى الْمُرْسَلِينَ (181)"));
        alsafatExes.add(new AlsafatEx("وتحية الله الدائمة وثناؤه وأمانه لجميع المرسلين."));
        alsafatExes.add(new AlsafatEx("وَالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ (182)"));
        alsafatExes.add(new AlsafatEx("والحمد لله رب العالمين في الأولى والآخرة، فهو المستحق لذلك وحده لا شريك له."));

        quran_explanation_37_adapter = new quran_explanation_37_adapter(alsafatExes ,QuranExplanation_37Activity.this);

        recyclerView = findViewById(R.id.rv_explanation_37);
        recyclerView.setLayoutManager(new LinearLayoutManager(QuranExplanation_37Activity.this));
        recyclerView.setAdapter(quran_explanation_37_adapter);


    }

}